In [28]:
from importlib import reload  # Python 3.4+
import Ising_model
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import uniform
from scipy.stats import binom
reload(Ising_model)

<module 'Ising_model' from '/Users/mw/PycharmProjects/xymodel-st-data/XY-MODEL/Ising_model.py'>

In [2]:
from Ising_model import IsingSystem

prior_pi = uniform.rvs(loc=0, scale=1, size=(nSpots, nTypes), random_state=None)

prior_Z = binom.rvs(1, prior_pi)

NameError: name 'nSpots' is not defined

In [7]:
N = prior_Z.shape[0]
L = int(prior_Z.shape[0] ** (1 / 2))
nbr = {i: ((i // L) * L + (i + 1) % L, (i + L) % N,
                        (i // L) * L + (i - 1) % L, (i - L) % N) \
                    for i in list(range(N))}

prop = prior_Z.copy()
energy_i = (prior_Z[idx] * prior_Z[nbr[idx], :]).sum(axis=0)
prop[idx] = 1 - prop[idx]
energy_f = -(np.repeat(prop[idx][np.newaxis, :], 4, axis=0) - prior_Z[nbr[idx], :]).sum(axis=0)

In [14]:
prior_Z[idx] 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
idx = 0
energy_i = (prior_Z[idx] * prior_Z[nbr[idx], :]).sum(axis=0)
energy_i

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
energy_i = (prior_Z[idx] * prior_Z[nbr[idx], :]).sum(axis=0)


NameError: name 'idx' is not defined

In [29]:
nSpots = 841
nTypes = 10 
from Ising_model import IsingSystem

prior_pi = uniform.rvs(loc=0, scale=1, size=(nSpots, nTypes), random_state=None)

prior_Z = binom.rvs(1, prior_pi)

xy_system_1 = IsingSystem(temperature=0.1, spin_config=prior_Z)
thetas_set = xy_system_1.equilibrate(show=True)


[-2  2  1 -2 -2  1 -2  2 -1 -4]
[ 0 -1  1  2 -2 -3 -4 -2 -1  2]
[ 0 -4 -1  1  2 -2 -2  3  3 -2]
[ 1  2 -3  2  1  1 -1 -2 -3  3]
[-2  2 -3 -1  3  0  3  4 -1 -1]
[ 1 -3  1  1  3 -1  2  2  0 -2]
[-1  0 -1 -3  3 -1  1 -3  1  3]
[ 2 -2  3 -3 -2 -3  2 -2  1 -3]
[ 2 -2  2  2  2 -4  2  1 -1  3]
[-1 -2  1  2  1  3 -2  1  4  3]
[ 2  3  1  1  1 -2 -3  3 -1 -2]
[ 1  2  2  3 -2 -2 -1 -4 -2  1]
[-4 -2  2 -3  3  2  2 -3 -2 -3]
[-2  2 -2  2  3 -3 -3 -3 -2 -1]
[-2 -1 -2 -2  3  4 -3 -3 -2 -3]
[ 2  2  2 -2 -2 -3 -4  3 -2 -3]
[ 4  3 -4  2  0 -1  2 -1 -2 -2]
[ 2  4 -3 -1  1 -2 -4  0  0 -1]
[ 3  1  1  2 -2 -3 -1  2 -1  0]
[-3  3 -3 -3  3 -1  3 -1  3 -2]
[-4 -3  3 -3  2  2  4  0  2 -2]
[ 1  1 -1 -3  1  4  0 -3 -3  1]
[ 2 -1  2 -3  1  2  3  1 -3  2]
[ 0  1  3  3 -3  2 -3 -2 -3 -1]
[-3  3  2  1  3  0  3 -1  1  0]
[ 1  1 -3  4  3 -3  0 -2 -4 -2]
[ 0 -2 -3  1 -4 -1  2 -1 -1  3]
[-2  2 -3  2  2 -3 -3  1 -1  1]
[ 1  3  3  1  1  2  3 -2 -2 -1]
[ 4 -3 -2 -3  3  2 -3 -2 -3  2]
[-1  0 -1  1 -2 -1  0  2 -1  1]
[-2 -3  

[ 0 -1  2 -1  0  1  1  0  1  1]
[ 1  2 -1  1  2  0  1 -1 -1  4]
[ 2 -2 -2  3  2 -1  0  2  1  3]
[-1  0  1 -1 -1  0 -1 -1  1  1]
[ 3  1  1  0  0 -1  2 -1  1  1]
[ 2  0  0  0  2 -1  1 -2  0  2]
[ 0  0 -1  0  0  2  0 -1 -1 -1]
[-3 -1 -1  3 -3  2 -3  2  1  2]
[-1  1 -2 -1  1 -1  3  2  2 -2]
[-2 -1  1  1 -1  2  0  1  0 -1]
[ 0  1  2 -2  1 -1 -2  0  2  0]
[-1 -2 -2  1  1  0  1 -2  2  1]
[ 2  1  3  1  0  3  0 -1  0 -2]
[ 2 -1  0  1 -2  0  0 -1 -1  0]
[ 1  4 -1  1  1 -1  0  0  1  1]
[ 0  1  0  0  1  1  2  0 -1  0]
[ 0 -1  0 -1 -1  1  2  0  1  1]
[0 0 0 1 0 0 0 0 1 0]
[ 0  2  3  0 -1 -1  0  2 -1 -1]
[-1 -1  2  1  1 -1  0  2 -2  0]
[ 0  1  0  0  1 -1  1  0 -1  0]
[ 0 -1  1  0 -1 -1  0  1 -1  1]
[ 0 -1 -1 -2 -1  1  2  0 -1 -1]
[ 1 -1  1  0  0 -1  0  0  0  0]
[ 0 -1  1  1 -1  1  0  2  1  0]
[-2 -1  0  2 -2  1  0 -2 -1 -3]
[ 2  0  3  1  1  1  2 -1  3  2]
[ 1  1  1 -1  2  1  1 -1  1  1]
[ 3  0 -1 -2  1 -1  0 -1  1  0]
[0 0 2 0 0 1 0 0 0 0]
[ 1  3  1  0 -2  4 -1 -1  0  3]
[ 3  0  0 -1  1  0  1  1 -1 

/Users/mw/PycharmProjects/xymodel-st-data/XY-MODEL/Ising_model.py:82: RuntimeWarning: invalid value encountered in double_scalars
  print(f'#sweep={k}')


[1 3 3 2 0 0 2 0 0 3]
[0 1 1 0 0 2 0 2 0 1]
[1 1 0 3 1 0 0 1 2 0]
[0 0 2 0 1 0 2 0 2 0]
[1 1 3 1 1 1 2 0 0 0]
[1 1 2 1 0 1 1 0 0 0]
[1 0 0 1 1 1 0 0 0 0]
[0 3 3 2 0 1 1 0 1 1]
[1 1 1 0 2 0 1 0 0 1]
[0 1 2 0 1 0 1 1 1 0]
[1 1 1 1 2 2 1 0 0 0]
[1 0 0 0 2 1 1 0 0 1]
[0 2 0 2 2 0 2 2 0 1]
[1 2 1 1 2 0 0 0 0 1]
[1 0 0 1 0 0 1 1 1 0]
[2 0 0 1 0 2 0 1 2 1]
[2 2 2 0 2 1 2 0 0 0]
[0 0 0 0 1 0 0 0 1 0]
[0 0 0 0 1 2 0 1 0 0]
[2 1 2 0 0 1 0 1 0 2]
[1 1 0 1 0 0 0 0 0 1]
[1 2 2 1 2 3 1 1 0 2]
[0 0 2 1 0 0 3 0 0 0]
[1 1 1 2 1 1 0 0 0 0]
[1 1 2 1 2 3 2 1 2 1]
[1 0 1 1 1 1 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 1 1 1 2 1 1 1 1 0]
[2 0 0 2 0 1 1 0 1 1]
[0 0 1 1 3 0 0 0 1 0]
[2 2 1 1 1 0 2 1 0 1]
[3 2 0 1 1 0 0 0 2 1]
[1 1 2 0 1 0 2 1 0 0]
[2 3 2 0 1 0 1 1 0 0]
[1 1 1 0 1 0 1 1 1 0]
[3 1 3 0 1 0 0 3 0 2]
[1 1 1 0 3 0 2 3 0 0]
[0 0 0 0 0 0 0 1 0 0]
[0 2 0 1 2 1 1 0 0 1]
[1 1 2 1 1 0 0 0 1 1]
[0 0 0 0 0 0 0 1 1 0]
[0 0 1 1 0 0 0 0 1 0]
[0 1 1 1 1 1 1 1 0 2]
[0 1 4 2 1 1 3 3 2 1]
[3 2 3 1 0 1 1 0 2 1]
[0 0 0 0 0

[1 2 1 2 0 0 1 1 2 2]
[1 1 1 0 0 0 0 0 0 1]
[0 0 2 1 0 1 1 3 0 1]
[0 1 2 0 1 2 1 0 1 0]
[4 2 2 2 1 3 2 2 3 4]
[3 3 2 1 3 0 1 3 3 1]
[1 1 3 2 0 0 2 2 0 2]
[0 0 2 0 3 0 0 0 0 0]
[2 1 0 0 1 0 2 0 0 0]
[2 0 0 0 0 1 2 1 0 0]
[0 0 1 2 0 0 0 1 0 2]
[0 1 0 0 0 0 2 1 0 0]
[0 1 2 1 1 2 1 1 2 2]
[1 2 0 0 1 1 0 0 0 1]
[0 3 1 1 1 0 0 0 0 2]
[1 0 0 1 1 1 0 1 0 1]
[0 1 0 1 0 0 0 0 1 0]
[0 2 2 2 3 0 0 2 1 1]
[2 3 2 1 0 2 3 3 0 4]
[1 1 2 0 1 0 1 0 1 0]
[1 2 1 2 2 1 2 0 4 1]
[0 1 1 2 2 0 1 2 1 0]
[0 0 0 1 0 0 0 0 1 0]
[1 2 0 0 0 1 1 1 0 1]
[1 0 0 0 0 1 0 1 0 2]
[0 0 0 2 0 1 0 0 0 1]
[2 1 1 1 1 1 0 1 2 0]
[3 1 3 0 1 1 1 1 1 2]
[0 0 0 1 0 0 0 0 0 0]
[0 2 2 3 0 1 0 0 1 0]
[2 2 2 3 1 0 2 3 2 1]
[0 1 0 0 0 0 2 2 2 2]
[0 0 2 1 3 3 1 3 2 2]
[2 3 2 2 0 1 4 0 2 2]
[0 0 0 1 1 2 0 0 0 0]
[2 2 0 3 1 1 4 2 1 1]
[1 0 1 2 1 2 1 0 2 0]
[0 1 0 2 0 0 0 1 0 1]
[1 1 2 1 0 0 1 0 0 3]
[1 1 3 1 2 1 1 1 0 0]
[1 1 2 1 2 1 0 2 3 3]
[4 3 2 2 4 1 2 1 3 0]
[2 3 3 4 2 3 3 2 1 3]
[1 1 3 1 3 2 1 1 1 2]
[0 3 0 0 2 2 0 1 1 1]
[0 0 1 0 1

[1 4 2 3 1 2 2 1 1 2]
[0 3 0 1 0 0 4 1 0 1]
[2 0 2 1 1 0 3 1 2 1]
[0 1 0 2 0 0 0 1 2 0]
[0 2 2 2 0 1 1 0 0 0]
[3 3 1 2 1 0 1 2 1 3]
[1 0 3 2 1 4 2 2 3 3]
[3 2 0 0 2 0 2 0 0 0]
[2 0 0 0 1 0 1 1 0 2]
[1 2 3 0 3 3 3 3 1 3]
[1 1 0 0 1 0 2 0 3 0]
[0 0 0 0 1 0 1 2 1 0]
[1 2 1 0 4 4 1 2 4 2]
[1 2 1 1 3 4 2 3 4 3]
[0 0 0 0 0 0 1 1 0 0]
[0 2 0 0 0 0 4 0 0 0]
[2 2 0 0 1 1 0 0 2 0]
[0 2 0 0 1 1 0 0 0 0]
[1 2 0 0 1 2 2 3 1 3]
[2 0 1 0 3 1 1 1 1 1]
[0 0 1 0 2 0 3 0 2 0]
[0 0 1 2 1 1 0 0 0 0]
[2 2 0 0 0 2 0 0 0 0]
[0 1 2 1 0 0 3 2 0 0]
[3 2 1 4 1 0 3 3 2 1]
[0 3 0 1 0 2 0 0 0 1]
[2 3 2 2 0 1 4 0 2 2]
[1 2 1 3 0 1 1 2 1 3]
[0 0 0 1 0 0 0 0 0 0]
[2 2 2 1 0 0 0 1 0 0]
[1 1 1 1 0 1 2 0 0 1]
[2 2 0 0 3 0 0 1 0 1]
[2 1 0 0 2 2 0 0 0 1]
[2 2 0 0 2 2 0 0 2 0]
[2 0 1 2 0 1 3 2 1 0]
[0 0 3 2 1 2 2 2 1 2]
[1 0 0 1 3 3 1 2 3 1]
[0 0 0 0 0 1 0 0 0 0]
[0 2 0 1 0 0 0 0 0 0]
[1 3 1 0 3 3 0 1 4 2]
[0 2 2 1 2 2 3 4 1 0]
[0 2 0 1 0 0 0 1 0 1]
[0 1 1 2 0 1 0 0 1 2]
[1 2 2 1 0 0 0 0 0 0]
[0 3 2 1 0 2 2 1 3 3]
[1 0 0 1 2

[0 1 1 0 2 0 2 0 0 0]
[0 1 0 2 0 0 1 0 0 2]
[0 0 0 1 0 0 0 0 0 1]
[0 0 0 1 0 0 0 1 1 0]
[0 1 0 2 3 0 1 1 3 2]
[0 0 0 1 0 0 0 1 0 0]
[2 0 3 1 0 0 0 1 0 2]
[2 1 1 1 0 2 2 1 0 2]
[0 0 2 0 1 0 2 0 0 0]
[0 0 0 0 0 0 0 1 1 0]
[0 2 0 0 1 0 2 4 2 0]
[0 0 2 0 3 0 2 1 0 0]
[1 1 1 0 0 1 3 0 0 3]
[1 0 2 1 0 0 0 0 0 1]
[0 2 1 2 3 0 0 3 1 0]
[0 0 0 1 0 0 3 0 0 1]
[0 0 2 2 2 3 0 0 0 1]
[2 2 0 4 0 2 4 3 0 0]
[1 0 2 2 1 1 0 0 0 1]
[1 0 0 0 0 0 1 0 0 1]
[0 0 2 1 0 1 1 0 1 1]
[1 0 2 0 0 0 0 0 0 0]
[2 0 1 0 3 0 2 1 0 0]
[0 0 0 1 1 1 0 2 3 0]
[0 1 0 0 1 1 0 1 1 1]
[2 0 0 1 0 0 0 2 1 0]
[0 3 0 0 0 1 1 0 0 0]
[2 1 2 1 2 2 1 1 1 3]
[1 1 1 0 0 1 1 1 1 2]
[0 2 0 0 1 0 0 2 0 0]
[0 0 1 0 0 0 0 0 4 2]
[4 4 0 2 0 0 1 1 1 0]
[1 2 0 0 0 1 2 2 2 1]
[1 2 1 3 3 0 0 3 3 3]
[0 0 1 1 1 0 0 1 1 4]
[2 0 0 0 0 1 0 3 0 0]
[0 0 0 0 0 0 0 4 0 0]
[1 1 0 2 1 0 0 1 1 0]
[1 0 2 1 0 2 1 0 0 2]
[1 1 2 0 1 0 0 0 0 3]
[0 0 0 0 0 0 0 0 2 0]
[1 0 1 0 1 2 0 0 1 0]
[2 4 0 0 2 1 0 2 1 1]
[0 0 0 1 1 1 0 0 0 0]
[0 0 1 3 1 1 0 2 1 3]
[0 0 0 0 0

[0 1 1 2 1 0 0 3 0 0]
[1 2 1 0 0 1 0 0 0 3]
[1 0 1 0 3 0 0 0 0 0]
[1 0 0 0 0 0 0 2 0 0]
[0 0 0 2 1 0 0 0 3 2]
[0 0 1 0 0 3 2 0 0 0]
[0 1 0 1 0 2 1 2 2 3]
[0 1 1 0 0 1 2 0 0 0]
[1 1 0 3 0 0 1 0 2 1]
[0 0 2 1 0 1 1 2 0 0]
[3 0 1 4 0 1 0 0 0 1]
[2 2 2 1 1 2 3 1 0 0]
[0 0 1 2 0 0 0 2 1 0]
[2 3 1 0 0 0 2 1 3 0]
[2 0 0 0 0 1 2 0 3 0]
[3 0 2 2 3 2 0 2 2 0]
[1 0 0 0 0 1 0 0 0 0]
[2 0 2 2 1 0 1 3 1 0]
[0 2 0 3 3 0 2 0 3 3]
[1 0 2 2 0 1 1 0 0 1]
[1 2 1 2 0 1 3 1 0 2]
[1 2 0 4 2 0 0 4 0 0]
[1 0 2 2 1 1 2 2 3 3]
[0 1 1 1 0 1 1 0 2 1]
[0 0 0 1 2 0 0 0 1 0]
[2 0 3 3 0 1 1 1 1 2]
[0 0 1 0 0 3 2 1 1 0]
[0 0 0 0 0 1 1 0 0 0]
[1 0 0 0 0 1 0 1 0 1]
[0 2 1 0 1 0 1 0 0 0]
[3 0 1 0 1 0 0 0 2 1]
[0 1 2 1 1 0 1 0 1 0]
[0 3 0 0 1 1 1 0 0 1]
[0 2 3 1 1 1 4 1 0 4]
[0 1 1 0 0 2 4 0 0 1]
[2 0 2 1 2 2 0 3 2 2]
[0 3 0 0 2 2 2 1 0 1]
[2 2 1 2 3 2 1 1 2 2]
[2 1 2 1 0 2 2 1 0 0]
[1 1 1 0 2 1 0 0 2 0]
[2 0 2 1 3 0 0 0 3 0]
[0 1 1 0 1 0 1 1 0 2]
[1 2 0 0 1 0 0 1 0 1]
[0 0 3 2 0 2 1 0 0 2]
[0 0 1 1 0 0 3 1 1 2]
[2 1 1 4 1

[0 0 0 2 2 2 1 0 0 0]
[1 3 1 0 0 0 2 1 3 0]
[1 3 1 0 0 1 0 1 0 1]
[0 2 0 2 4 0 1 0 1 1]
[0 0 2 4 1 2 2 1 1 0]
[1 0 2 1 0 0 0 0 2 0]
[4 1 0 0 0 2 0 0 0 0]
[4 4 0 0 0 0 1 0 1 0]
[1 0 2 0 2 1 1 1 0 1]
[1 1 2 0 2 0 1 1 0 2]
[1 2 2 4 1 1 0 1 0 2]
[1 0 0 0 0 0 0 0 1 0]
[1 1 0 0 0 3 0 0 1 2]
[0 0 0 2 0 1 0 1 1 1]
[0 0 1 0 0 2 0 1 0 0]
[0 2 1 0 0 0 2 0 2 1]
[3 3 0 0 2 0 3 0 1 1]
[0 2 1 0 1 0 2 0 0 0]
[3 1 0 0 2 1 0 2 2 2]
[2 1 2 3 1 0 1 0 0 0]
[1 1 1 1 0 2 1 1 0 0]
[3 1 1 1 2 0 0 0 2 3]
[2 2 0 0 1 1 1 2 1 2]
[3 1 0 0 0 2 0 2 0 1]
[1 0 3 1 2 1 0 0 2 2]
[4 0 0 1 4 0 1 1 0 2]
[0 0 0 1 0 2 0 0 0 0]
[1 2 0 1 0 1 1 2 0 0]
[2 2 1 0 0 1 0 1 1 1]
[0 4 0 0 0 3 0 0 0 1]
[0 1 1 1 2 2 0 2 2 0]
[0 1 3 0 1 0 2 0 0 0]
[0 0 0 2 0 0 1 1 0 0]
[0 0 0 1 2 1 1 0 0 2]
[0 1 0 1 1 1 0 0 1 1]
[0 2 2 0 4 2 1 0 2 0]
[0 2 0 0 1 0 3 2 2 0]
[0 0 3 1 0 1 1 0 2 0]
[0 0 0 3 0 0 3 0 2 0]
[1 1 1 1 1 0 0 0 2 0]
[0 1 1 2 1 1 2 2 0 0]
[1 0 0 1 0 0 0 1 0 0]
[0 1 0 0 0 0 2 1 0 0]
[0 0 1 2 0 0 1 0 2 0]
[0 0 2 0 1 2 1 1 0 0]
[3 1 3 2 1

[1 2 0 0 2 0 2 3 1 0]
[1 1 0 0 0 0 0 1 0 0]
[0 0 1 1 2 1 0 0 0 1]
[4 0 0 2 2 0 1 2 2 1]
[2 2 4 2 0 0 2 3 1 1]
[2 0 0 1 1 0 2 1 0 0]
[0 0 0 0 1 1 2 1 1 2]
[0 2 1 0 0 0 3 4 0 1]
[2 2 0 0 2 0 2 1 1 0]
[0 1 2 0 0 0 2 2 0 0]
[0 1 3 2 0 1 1 0 1 0]
[0 0 1 0 0 0 2 1 1 2]
[0 1 0 3 1 0 0 0 1 1]
[3 2 0 3 1 0 0 3 0 2]
[2 0 0 0 2 1 1 0 0 1]
[1 0 3 2 0 0 0 1 1 0]
[2 0 0 1 4 2 2 2 1 1]
[0 3 3 0 0 1 1 2 0 0]
[3 1 0 0 2 2 1 0 0 2]
[0 1 0 1 2 1 0 1 0 2]
[1 0 0 1 0 0 0 0 0 2]
[0 0 0 0 0 0 2 0 2 0]
[1 0 1 1 1 0 1 0 0 0]
[1 0 0 2 1 2 2 1 3 1]
[3 1 0 2 2 0 3 0 0 3]
[0 0 1 1 2 0 0 0 0 2]
[0 1 0 0 0 1 1 0 0 0]
[3 1 0 0 0 1 3 0 1 2]
[1 1 1 1 0 3 1 1 0 0]
[2 0 1 0 2 0 0 0 2 1]
[1 1 0 0 1 1 2 0 2 2]
[0 0 0 1 0 1 0 3 0 1]
[0 1 2 0 2 2 0 2 1 1]
[0 0 1 1 2 2 0 0 1 0]
[1 0 2 0 0 1 0 0 2 0]
[0 0 1 2 2 0 0 0 2 0]
[0 0 0 1 0 0 0 0 0 0]
[1 0 0 2 1 2 0 1 1 0]
[1 3 0 0 3 1 0 2 2 0]
[1 1 3 0 3 0 1 1 1 1]
[1 0 1 0 2 2 0 0 1 0]
[0 0 0 0 0 3 3 0 0 3]
[0 0 0 1 1 1 0 1 0 3]
[1 0 3 0 2 0 0 0 2 1]
[0 1 0 2 0 0 0 0 1 0]
[1 2 3 0 2

[2 1 0 0 0 1 0 0 0 0]
[1 2 2 0 1 0 0 2 1 1]
[3 0 1 0 0 1 2 1 2 1]
[1 1 0 0 0 0 0 0 1 1]
[2 1 1 1 0 0 3 2 1 1]
[2 0 1 3 1 1 2 1 2 1]
[3 2 2 0 2 0 0 3 3 1]
[2 0 0 3 0 2 2 2 2 0]
[0 0 1 1 2 2 0 0 0 0]
[0 0 2 0 0 0 0 1 0 0]
[0 3 0 0 0 1 1 2 0 1]
[0 2 1 1 2 1 1 0 1 2]
[0 3 1 0 0 2 2 1 0 3]
[0 2 1 1 1 1 2 2 0 2]
[2 0 3 2 3 0 1 1 2 2]
[2 1 0 0 0 0 1 1 0 0]
[2 1 1 0 2 1 1 1 1 1]
[0 0 0 2 2 1 1 1 0 3]
[4 0 0 0 2 1 4 0 1 3]
[2 0 1 1 2 1 0 0 1 0]
[1 0 0 1 1 0 0 1 0 0]
[2 1 0 2 0 4 2 0 2 3]
[1 1 1 1 0 1 0 0 0 0]
[0 0 0 1 2 2 0 2 0 0]
[1 0 1 1 0 1 0 3 0 0]
[0 0 3 0 0 2 3 0 2 2]
[1 0 1 0 0 0 1 0 0 1]
[2 1 0 1 1 1 0 1 1 2]
[0 2 0 2 3 1 0 2 0 0]
[3 0 2 2 0 1 2 2 1 2]
[2 1 3 1 2 2 0 1 2 2]
[1 1 1 0 1 0 1 2 1 2]
[0 0 0 0 2 0 1 1 1 0]
[2 2 1 3 1 2 0 1 3 0]
[0 1 0 0 1 1 0 3 1 1]
[0 2 0 2 0 2 1 0 1 3]
[0 0 2 0 0 0 0 2 0 0]
[1 1 0 2 2 1 1 2 1 1]
[2 0 0 0 2 0 0 1 0 0]
[0 0 3 2 0 0 0 1 0 0]
[2 1 2 0 1 1 1 0 0 0]
[1 0 2 2 2 0 0 3 0 0]
[0 1 1 0 1 2 2 0 1 1]
[0 0 0 2 0 2 3 0 1 2]
[1 2 0 2 2 2 0 0 1 1]
[2 2 0 2 1

[1 1 0 0 3 3 2 3 2 0]
[0 0 2 1 1 1 0 3 0 2]
[0 0 3 3 2 3 0 1 2 1]
[2 1 3 0 1 2 0 2 2 1]
[0 2 2 0 0 0 3 0 3 0]
[1 1 1 2 2 1 3 0 0 1]
[0 4 0 0 0 1 1 4 2 0]
[0 1 0 1 1 1 0 0 0 0]
[1 2 3 2 0 0 1 0 0 0]
[2 0 1 4 0 0 1 0 0 2]
[1 1 1 2 0 1 2 0 1 0]
[0 3 0 0 2 1 0 0 0 1]
[0 1 0 2 0 2 1 0 0 2]
[2 0 0 4 2 1 0 0 0 2]
[0 2 0 0 3 0 0 1 2 2]
[0 0 1 0 1 0 0 1 0 0]
[0 3 0 0 0 1 0 0 0 0]
[3 1 0 0 0 0 0 1 0 0]
[2 0 1 1 0 0 1 0 1 1]
[0 0 1 2 2 2 2 1 2 1]
[2 1 0 2 0 0 0 0 2 0]
[2 2 2 0 2 1 0 2 1 2]
[0 1 0 0 2 0 1 2 2 0]
[1 0 1 3 0 0 0 1 2 0]
[1 0 1 0 1 0 1 2 3 3]
[0 1 0 0 3 0 1 3 3 2]
[2 2 0 0 0 0 0 0 1 1]
[1 4 0 1 2 1 0 1 1 1]
[1 2 0 0 4 0 3 0 1 2]
[0 0 3 0 0 0 2 0 0 2]
[0 1 0 0 2 1 3 0 1 4]
[1 2 1 0 1 1 2 3 0 0]
[2 0 0 1 0 3 1 0 0 0]
[0 1 0 2 0 1 0 3 0 0]
[0 0 0 1 1 0 0 2 1 2]
[0 1 3 1 1 1 1 0 2 2]
[0 0 0 2 1 0 0 0 0 2]
[1 3 2 1 3 0 0 0 2 1]
[1 0 0 1 0 0 2 0 0 0]
[0 0 4 1 2 4 0 0 2 1]
[0 3 1 0 0 1 0 2 1 3]
[0 0 0 1 1 0 1 3 1 0]
[1 1 0 0 1 1 0 2 1 3]
[1 3 1 0 0 2 1 0 0 1]
[0 0 0 0 1 0 0 1 0 1]
[0 1 0 2 0

[1 0 0 1 0 0 3 0 0 2]
[1 0 0 2 2 2 0 0 1 0]
[1 1 1 0 0 2 1 0 0 2]
[0 2 0 1 0 1 0 2 0 0]
[2 2 0 1 0 0 0 0 0 1]
[2 0 1 1 1 0 0 2 0 2]
[1 2 0 0 0 2 1 1 1 1]
[3 1 0 0 1 0 0 1 1 1]
[1 0 1 3 1 4 0 0 1 0]
[0 2 2 2 0 1 0 2 2 1]
[1 1 1 1 3 0 0 1 1 1]
[0 2 0 0 2 1 2 1 4 0]
[1 2 0 1 0 0 0 0 3 0]
[0 0 0 0 0 3 2 0 2 1]
[1 0 0 1 1 0 0 0 0 1]
[1 1 0 1 1 0 0 3 1 2]
[0 0 0 2 0 0 2 0 1 2]
[0 0 0 2 0 0 2 0 0 0]
[0 0 0 0 0 0 2 1 0 2]
[0 1 2 0 1 2 2 0 2 1]
[3 0 1 2 0 1 1 1 2 1]
[2 1 0 2 2 3 3 2 0 0]
[1 2 1 1 0 1 2 0 0 0]
[3 0 3 0 2 0 3 0 1 4]
[1 1 0 1 0 1 2 3 0 0]
[0 3 1 0 2 0 0 1 1 2]
[2 0 1 2 2 1 0 0 1 0]
[1 1 0 0 0 2 2 2 0 1]
[1 1 2 2 2 1 0 0 1 1]
[1 0 0 2 0 2 0 0 0 0]
[1 1 0 3 0 0 3 0 1 0]
[3 2 1 1 1 3 1 2 0 0]
[2 0 1 2 3 0 1 2 2 1]
[0 1 0 1 1 2 0 0 0 1]
[0 1 0 0 2 1 0 3 1 1]
[0 2 0 1 0 3 0 1 1 0]
[3 1 0 0 2 1 1 0 0 4]
[1 0 1 1 0 0 2 0 0 0]
[1 0 0 2 3 0 1 2 2 0]
[0 0 1 0 1 0 1 1 0 1]
[0 1 1 0 0 2 2 0 0 1]
[1 0 1 0 3 2 1 1 0 0]
[2 1 0 2 0 1 1 2 1 1]
[1 2 2 2 2 4 2 0 2 2]
[0 1 0 3 1 1 0 0 2 1]
[0 3 0 0 0

[2 1 2 1 2 1 1 0 2 2]
[0 3 1 0 0 0 0 0 0 2]
[2 4 1 0 0 1 0 0 0 2]
[0 2 3 0 3 3 1 1 1 3]
[0 4 2 4 0 1 2 0 0 2]
[0 2 0 0 1 2 1 2 1 1]
[0 0 1 1 2 0 4 0 0 0]
[0 1 1 0 2 1 0 0 0 2]
[3 0 1 0 1 2 0 0 3 2]
[0 1 0 0 1 0 0 2 0 0]
[2 1 1 1 1 2 2 2 1 2]
[1 1 1 1 1 0 1 0 1 0]
[2 1 1 1 2 4 0 1 1 0]
[0 0 3 1 0 0 0 1 0 2]
[0 1 0 2 0 1 0 1 1 1]
[1 0 1 1 0 0 2 0 0 0]
[0 1 1 0 1 0 3 0 0 1]
[0 0 3 0 1 1 0 4 0 0]
[0 1 0 2 1 4 1 4 0 1]
[0 0 3 0 2 0 0 0 0 2]
[0 0 1 4 2 1 1 1 1 1]
[1 0 0 2 0 0 2 0 0 2]
[2 0 1 2 0 1 0 0 1 1]
[1 0 0 1 2 0 2 1 0 1]
[1 3 0 1 2 1 3 1 3 0]
[2 0 3 2 1 1 1 0 0 3]
[2 1 0 1 3 2 2 0 2 1]
[2 1 0 0 0 0 2 0 4 1]
[2 0 0 0 0 1 0 0 0 0]
[0 0 2 0 0 1 0 0 0 1]
[0 2 0 0 0 1 1 0 0 0]
[0 0 0 2 2 0 0 2 1 0]
[1 1 0 2 0 0 0 0 0 0]
[0 1 2 4 2 0 1 2 1 0]
[3 1 1 0 1 0 4 0 0 3]
[0 3 0 2 0 0 0 0 3 0]
[1 2 0 0 1 0 1 0 1 0]
[1 0 0 0 0 1 0 1 0 1]
[3 1 0 0 0 1 0 0 0 0]
[3 0 2 1 1 1 1 0 1 2]
[1 0 1 1 0 0 0 0 0 0]
[0 1 1 0 0 1 2 1 1 1]
[1 1 0 0 0 0 0 0 0 1]
[1 0 1 2 2 2 0 1 1 2]
[1 1 4 3 2 0 1 0 1 0]
[1 0 0 1 2

[0 3 1 0 1 2 2 1 0 1]
[1 2 2 1 1 0 0 2 3 0]
[0 3 1 1 0 0 2 0 0 0]
[0 0 0 1 1 2 1 1 4 3]
[0 1 3 0 0 0 0 0 2 3]
[0 0 0 1 0 0 0 1 0 1]
[1 0 1 1 1 2 1 0 0 1]
[3 0 3 0 0 0 0 0 0 0]
[1 0 4 1 0 0 0 0 0 2]
[0 0 1 1 0 0 1 0 1 2]
[0 0 0 0 0 1 1 2 1 1]
[0 0 0 2 1 0 1 1 1 2]
[2 0 0 1 2 1 2 1 0 0]
[1 0 1 0 1 2 2 0 0 2]
[3 0 0 3 1 2 1 0 0 0]
[0 1 2 0 0 1 2 2 1 1]
[4 1 0 1 3 0 0 1 3 0]
[2 1 3 3 1 3 1 2 2 1]
[0 1 1 0 1 2 3 0 2 1]
[0 1 0 0 0 1 0 0 0 3]
[1 0 0 1 0 0 1 1 0 0]
[2 0 1 0 0 2 1 2 1 0]
[0 0 0 1 0 0 2 0 1 0]
[1 2 0 0 0 1 0 0 0 2]
[0 1 1 1 0 0 1 1 1 0]
[2 1 0 0 0 0 0 0 2 0]
[0 1 0 1 0 1 0 2 0 0]
[1 1 2 0 1 1 2 0 0 2]
[1 0 0 0 0 1 0 1 2 0]
[3 0 0 0 0 0 0 1 3 0]
[0 0 0 3 0 0 0 1 2 0]
[2 2 1 1 0 0 1 0 0 3]
[0 2 0 2 1 1 1 0 0 2]
[2 0 2 0 1 1 2 0 0 1]
[0 1 1 1 0 0 3 0 0 1]
[1 1 2 1 1 0 2 1 0 2]
[3 0 1 1 0 3 3 0 2 0]
[2 2 0 2 1 2 3 2 2 0]
[1 0 2 2 0 1 0 0 1 2]
[0 0 0 0 0 0 0 1 0 0]
[1 0 1 1 1 0 3 0 2 1]
[0 0 1 0 1 1 2 0 0 0]
[0 3 1 3 2 0 1 1 1 2]
[0 0 0 3 1 1 4 0 1 1]
[0 0 2 2 0 3 0 3 0 0]
[0 2 0 0 1

[1 0 4 0 1 3 1 1 2 0]
[2 0 2 0 2 0 2 2 0 1]
[0 2 0 0 1 0 0 3 4 2]
[0 2 1 0 1 0 0 0 0 2]
[2 2 0 0 1 0 1 2 1 1]
[1 1 2 1 1 0 0 2 2 0]
[2 2 2 0 0 2 0 1 3 0]
[0 0 2 2 0 0 1 0 0 3]
[1 0 2 0 2 2 1 0 0 1]
[2 1 0 0 2 1 2 0 1 1]
[3 1 1 0 4 0 2 0 1 0]
[1 0 2 2 0 1 1 1 0 0]
[0 0 0 0 0 0 1 0 1 0]
[1 2 1 0 0 0 0 0 3 0]
[0 2 2 1 2 0 1 0 0 0]
[0 0 1 0 1 0 1 2 1 0]
[0 1 0 0 0 0 0 0 0 0]
[0 0 1 2 0 0 0 0 1 1]
[0 0 1 0 0 1 0 0 0 2]
[0 0 2 0 0 0 0 0 1 1]
[0 0 1 1 1 0 0 3 3 0]
[1 2 0 3 1 1 1 0 4 0]
[0 1 0 0 0 0 0 0 2 0]
[2 3 0 0 1 3 0 2 0 0]
[4 0 0 3 1 1 1 1 1 0]
[2 2 0 1 0 1 1 3 0 1]
[1 0 1 0 3 0 1 3 3 0]
[0 2 0 0 1 1 0 2 1 0]
[1 0 2 3 0 0 0 1 3 2]
[1 2 1 1 0 3 1 0 2 0]
[0 0 0 1 1 2 2 2 1 0]
[0 0 1 1 0 0 2 1 1 1]
[2 0 2 1 0 0 0 0 0 0]
[1 2 2 1 0 0 0 3 0 1]
[0 0 0 1 1 0 0 1 0 1]
[3 2 2 0 1 3 1 0 1 0]
[0 1 0 0 2 0 0 2 0 1]
[0 2 2 0 4 0 2 3 1 3]
[0 0 0 1 1 2 0 2 0 3]
[3 0 0 0 2 0 1 2 2 1]
[0 0 0 1 0 1 0 3 2 2]
[0 1 2 2 0 1 0 0 0 3]
[0 3 0 1 2 2 0 2 0 0]
[3 0 0 3 0 2 0 0 0 0]
[2 0 0 2 3 0 0 0 1 0]
[1 0 0 0 1

[2 0 0 0 0 1 1 0 0 1]
[2 2 1 0 2 1 2 0 4 2]
[0 0 2 2 1 1 0 1 0 0]
[0 1 3 2 0 1 1 1 0 2]
[2 0 0 0 2 1 0 0 1 0]
[1 0 0 4 1 0 2 2 1 0]
[1 1 1 1 2 1 1 1 0 1]
[1 1 4 3 2 2 1 2 1 1]
[0 2 2 0 1 4 1 1 2 0]
[1 0 3 2 0 0 1 0 0 0]
[1 0 2 0 1 0 2 0 2 0]
[1 0 3 0 0 0 2 0 2 0]
[1 0 0 2 0 1 0 0 1 0]
[0 1 0 0 2 0 0 0 2 0]
[0 0 1 0 0 0 0 2 0 1]
[0 3 0 2 4 0 1 3 3 2]
[0 1 0 2 1 0 0 0 0 0]
[3 1 0 0 1 1 3 1 0 1]
[1 0 0 2 0 1 0 3 0 0]
[1 0 1 0 1 0 0 1 0 1]
[1 1 0 2 0 2 0 3 2 1]
[2 1 1 2 0 1 1 0 2 0]
[0 0 0 0 0 1 0 1 2 2]
[3 0 0 0 1 1 1 0 1 0]
[1 1 0 1 1 1 1 0 0 1]
[2 0 3 2 1 0 1 0 0 0]
[0 1 3 1 0 0 0 3 3 0]
[0 1 3 2 0 1 1 1 0 2]
[1 1 0 0 0 2 0 2 0 2]
[1 2 1 1 2 1 1 2 1 0]
[1 1 1 2 1 1 1 0 1 0]
[1 0 0 0 1 0 0 0 0 0]
[0 3 2 0 0 2 0 2 1 0]
[0 3 0 0 0 0 0 0 0 2]
[2 1 2 2 2 1 3 0 2 0]
[0 1 1 0 3 1 0 0 0 1]
[1 0 1 0 2 0 0 0 0 1]
[0 0 0 0 0 0 1 2 1 0]
[0 1 0 1 0 0 3 1 0 3]
[0 1 3 4 0 1 1 1 0 0]
[0 0 2 1 0 1 1 0 2 0]
[1 1 1 0 1 0 1 0 0 0]
[2 2 2 0 0 0 2 0 1 1]
[3 1 0 0 0 0 3 0 0 0]
[2 1 0 1 0 0 0 3 0 3]
[2 0 1 0 2

[1 1 0 0 2 0 0 2 1 1]
[2 1 0 0 2 2 0 2 1 0]
[0 2 1 2 0 0 0 2 1 0]
[2 0 0 1 1 2 3 3 0 2]
[0 2 0 0 2 2 0 1 1 2]
[4 0 0 0 1 1 2 0 0 1]
[0 0 0 1 1 1 0 1 1 0]
[2 1 0 2 2 3 2 2 0 1]
[1 2 0 0 0 1 0 2 1 0]
[1 3 2 2 2 3 1 4 0 4]
[0 0 2 1 2 0 0 1 2 0]
[1 1 2 2 1 3 2 2 1 1]
[2 0 1 2 0 0 1 1 1 2]
[0 0 2 0 0 0 1 0 0 2]
[1 0 0 2 2 2 1 0 2 0]
[0 0 2 2 2 0 1 0 0 1]
[2 0 2 1 1 0 1 0 2 0]
[0 0 0 2 0 1 1 0 2 0]
[2 0 0 2 0 0 0 1 0 2]
[0 2 1 0 0 0 0 0 2 0]
[2 1 0 0 1 0 0 0 1 1]
[0 3 0 0 2 1 0 2 1 0]
[1 0 0 0 0 1 0 2 0 0]
[1 0 3 0 0 0 1 1 1 3]
[0 3 0 0 3 2 0 0 0 0]
[0 2 0 1 0 0 1 2 0 0]
[0 3 2 0 1 1 1 3 0 1]
[1 0 2 2 0 1 0 4 1 0]
[0 0 0 0 0 1 0 0 2 2]
[0 1 0 2 0 2 1 1 2 0]
[0 2 2 0 0 0 0 2 0 2]
[0 0 1 0 2 1 1 3 2 2]
[3 0 2 0 1 0 0 1 1 3]
[1 0 0 1 0 3 0 0 0 0]
[0 0 0 1 3 0 1 0 3 2]
[1 2 2 3 1 0 2 1 1 1]
[0 2 2 1 0 2 2 1 1 0]
[0 1 0 1 0 1 0 2 1 1]
[1 1 2 3 2 1 2 0 0 1]
[2 1 1 0 1 0 0 0 4 0]
[0 0 0 0 0 2 1 0 1 1]
[2 1 0 0 1 0 0 1 1 0]
[0 1 0 1 0 1 2 1 0 2]
[1 3 2 0 2 0 0 1 2 0]
[2 1 0 2 0 0 0 3 1 2]
[0 1 0 2 0

[3 0 2 1 0 2 1 0 0 0]
[3 2 2 1 3 0 0 2 0 1]
[2 2 2 0 1 3 0 0 0 0]
[1 1 0 1 2 0 0 1 2 2]
[1 2 2 0 1 1 1 0 1 0]
[0 1 1 0 1 2 1 3 1 1]
[1 1 1 1 0 1 0 2 2 3]
[0 0 0 0 2 0 1 2 1 1]
[3 0 2 1 0 2 0 1 1 0]
[1 1 0 1 2 1 2 0 0 0]
[0 0 2 0 0 2 0 2 2 1]
[0 1 0 0 2 1 1 1 0 1]
[0 0 0 2 0 0 1 1 0 3]
[0 0 1 1 0 2 1 2 0 1]
[1 1 2 1 2 2 0 0 0 0]
[0 0 0 2 1 2 0 0 0 2]
[0 1 1 2 0 0 0 1 2 1]
[1 1 0 1 0 0 1 0 1 3]
[0 3 1 0 2 1 1 0 0 1]
[3 0 1 2 1 1 1 0 1 0]
[0 1 0 1 0 1 1 2 0 2]
[2 0 0 0 3 1 1 1 0 1]
[0 0 0 1 2 1 3 1 2 1]
[0 0 1 1 0 0 1 2 2 0]
[1 2 2 3 1 0 2 1 1 1]
[0 2 0 2 2 0 1 1 0 3]
[0 2 1 0 1 1 0 3 0 2]
[2 0 4 0 2 0 1 1 0 2]
[0 0 3 2 1 0 0 0 2 0]
[0 2 2 0 1 0 0 0 2 0]
[0 2 0 0 2 0 0 2 0 1]
[0 1 0 0 2 0 3 0 1 1]
[2 0 0 1 1 2 1 0 0 1]
[0 1 0 1 1 0 0 2 0 0]
[0 2 1 1 0 3 0 0 0 0]
[0 3 2 2 1 2 1 3 0 2]
[1 2 1 0 0 0 1 0 0 3]
[1 1 0 2 2 0 0 1 0 1]
[1 3 2 3 2 0 1 2 0 0]
[1 0 0 1 0 2 0 3 1 1]
[2 0 2 0 2 2 4 0 2 0]
[0 1 0 0 2 2 1 2 0 2]
[4 0 2 3 3 2 3 3 1 1]
[0 1 0 0 1 2 2 0 2 0]
[1 2 0 2 0 0 2 1 1 1]
[0 0 1 3 1

[3 0 0 1 0 2 2 0 3 1]
[1 2 2 1 0 1 1 1 0 2]
[0 0 1 2 0 1 1 0 0 1]
[3 1 2 2 0 3 0 2 1 2]
[3 0 2 0 0 2 0 0 0 0]
[3 3 1 1 0 0 2 3 1 1]
[1 0 1 1 0 1 0 0 0 1]
[0 0 2 2 3 4 0 2 3 2]
[0 3 0 0 0 1 0 1 0 2]
[0 2 0 1 1 1 0 2 0 2]
[2 0 1 2 0 1 2 1 0 0]
[2 2 0 1 0 0 1 2 0 1]
[0 0 0 0 0 1 0 1 1 1]
[2 0 0 0 1 0 1 0 2 1]
[0 1 1 1 0 3 0 0 1 2]
[1 0 1 1 0 0 0 0 0 0]
[1 0 0 0 3 0 3 1 0 0]
[0 2 0 0 0 1 3 0 1 0]
[0 3 0 0 1 2 0 0 0 3]
[0 0 0 1 2 1 3 3 1 2]
[1 3 0 2 1 0 1 0 0 1]
[0 0 0 1 0 1 0 0 1 0]
[0 0 1 0 0 0 2 1 2 1]
[2 2 1 3 3 0 0 1 1 0]
[2 3 1 2 0 0 1 1 1 0]
[2 3 0 1 0 0 2 0 0 0]
[2 0 2 1 0 0 2 0 0 0]
[1 2 0 1 0 0 0 3 0 0]
[0 0 1 0 1 1 0 0 4 2]
[1 1 0 0 0 1 2 2 0 2]
[1 3 1 1 0 1 0 0 2 1]
[3 1 2 2 1 1 1 1 1 2]
[2 2 1 2 3 1 2 0 1 2]
[1 0 2 2 1 1 3 1 1 2]
[1 0 0 0 3 0 1 0 0 1]
[0 2 0 0 0 1 2 3 1 3]
[0 0 2 0 2 2 4 1 0 1]
[1 1 0 0 0 2 1 0 2 0]
[2 0 0 0 2 0 0 3 2 0]
[0 1 0 2 1 2 0 1 0 2]
[0 2 1 1 1 1 1 1 0 2]
[0 0 1 0 1 1 0 2 3 3]
[1 0 1 1 2 0 3 1 0 0]
[0 0 0 1 1 0 1 1 0 1]
[2 3 1 0 0 1 2 1 2 0]
[3 1 1 0 0

[1 0 3 0 0 0 0 0 0 0]
[3 2 0 0 0 0 1 3 1 0]
[2 0 0 1 0 1 0 0 0 2]
[0 0 1 1 2 2 0 0 0 1]
[0 0 1 1 1 2 2 0 1 3]
[1 1 2 0 1 1 0 1 0 1]
[0 3 0 3 1 1 0 0 2 2]
[1 1 0 3 1 3 1 0 2 2]
[1 1 0 2 2 2 2 0 0 0]
[0 0 1 0 1 0 0 3 1 2]
[0 0 0 2 0 3 1 0 2 0]
[0 2 0 1 1 1 0 0 2 0]
[1 0 0 1 1 1 0 3 2 3]
[1 0 2 2 0 0 0 0 3 1]
[0 0 1 0 2 0 4 3 0 1]
[0 2 0 0 0 0 0 0 1 1]
[2 1 1 4 0 0 0 1 1 0]
[1 1 1 2 0 0 1 1 2 0]
[3 0 2 1 0 2 2 2 1 2]
[1 1 1 0 0 1 0 3 2 2]
[2 1 3 2 1 0 1 1 0 3]
[1 0 2 0 2 1 3 0 0 0]
[2 1 1 0 0 1 2 0 2 0]
[0 1 1 0 1 0 2 0 1 1]
[0 0 1 0 0 0 0 1 1 1]
[0 1 0 0 1 0 0 0 1 2]
[2 0 3 1 1 3 1 1 0 0]
[1 2 0 0 2 0 0 0 3 1]
[0 0 1 0 1 2 1 0 0 1]
[0 2 0 2 0 0 1 0 2 0]
[2 0 1 1 0 1 1 0 0 0]
[0 0 1 1 0 0 0 0 0 0]
[0 0 1 3 1 0 0 0 0 0]
[1 1 1 0 0 1 3 0 1 0]
[2 1 1 0 1 2 0 0 2 0]
[1 1 3 2 0 1 3 0 1 1]
[2 2 3 0 1 1 3 1 1 0]
[1 2 0 1 2 1 1 1 1 2]
[4 0 1 0 2 1 3 1 2 0]
[2 2 1 1 0 0 2 2 1 2]
[4 1 1 1 0 1 1 0 1 1]
[0 0 0 0 0 2 0 0 0 0]
[2 1 2 1 0 2 2 0 3 1]
[0 2 1 1 4 2 2 1 1 1]
[1 2 0 2 1 1 3 0 0 0]
[1 1 2 1 1

[0 0 1 2 0 0 1 3 0 1]
[1 1 0 1 0 0 1 2 2 1]
[0 2 1 0 2 0 1 1 2 0]
[0 0 0 0 1 1 0 1 0 0]
[1 1 2 2 3 0 2 0 0 2]
[1 1 3 0 1 2 4 0 1 0]
[3 1 0 4 0 3 1 0 0 0]
[1 2 1 1 0 1 2 3 3 0]
[0 0 0 0 1 0 0 0 0 3]
[2 0 1 0 2 2 0 2 2 0]
[0 0 0 2 1 0 0 2 0 2]
[2 0 2 2 2 2 2 0 0 0]
[0 1 1 0 0 0 0 0 1 1]
[2 2 2 1 4 2 2 0 1 1]
[0 0 0 0 2 0 0 0 0 0]
[3 1 0 2 0 2 2 2 0 2]
[0 2 2 0 0 1 1 0 3 0]
[1 1 3 2 0 0 0 0 1 0]
[3 2 1 2 0 0 2 2 2 3]
[1 1 2 0 0 0 1 1 0 0]
[1 0 2 1 0 0 1 0 0 0]
[0 0 0 3 2 0 0 1 0 3]
[0 2 0 3 0 2 3 1 2 1]
[0 0 0 1 0 0 0 2 0 0]
[1 0 1 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 3 0 3]
[1 0 3 0 0 1 0 0 2 0]
[1 2 2 0 1 1 2 0 0 0]
[1 1 0 0 0 0 1 0 2 1]
[0 1 1 0 1 2 2 0 0 1]
[0 0 1 1 0 0 0 0 0 0]
[0 0 0 0 1 0 0 1 0 2]
[3 1 2 0 0 0 0 1 0 0]
[0 2 2 1 1 0 0 0 0 1]
[2 1 2 2 1 1 2 2 0 0]
[1 4 2 2 0 2 0 0 1 0]
[0 0 2 1 2 1 1 0 1 2]
[0 0 0 0 2 2 0 0 0 0]
[1 1 0 0 0 0 1 1 1 0]
[1 2 1 0 0 1 3 1 4 0]
[0 2 3 0 3 0 0 3 0 1]
[1 0 0 2 0 2 0 0 0 0]
[0 0 1 1 1 0 0 0 2 0]
[1 0 1 0 0 0 0 1 0 0]
[0 2 0 0 0 0 3 0 3 1]
[1 0 1 0 1

[0 1 1 3 0 1 0 0 1 0]
[0 0 0 0 3 0 2 0 2 1]
[0 0 1 0 0 1 3 3 1 0]
[2 2 3 3 1 1 2 1 1 1]
[0 0 0 0 2 2 3 1 1 1]
[0 1 3 1 3 2 0 1 1 3]
[2 3 2 3 0 1 2 4 1 2]
[0 1 1 0 0 0 0 0 0 0]
[0 1 0 0 1 0 1 0 0 1]
[1 0 2 0 3 3 0 1 0 1]
[2 3 3 0 0 0 0 1 0 1]
[3 2 0 1 0 0 0 0 0 0]
[0 2 1 1 2 0 1 1 2 3]
[3 2 3 1 1 2 2 0 0 0]
[0 2 0 1 0 0 0 2 0 0]
[0 1 1 1 0 1 0 1 1 2]
[1 1 0 1 1 1 2 0 2 2]
[2 1 2 0 0 1 1 1 0 0]
[0 2 0 0 0 1 0 1 0 2]
[0 0 3 0 3 0 2 1 0 3]
[1 1 1 1 2 0 1 0 1 2]
[1 0 0 1 1 3 0 0 1 0]
[0 1 0 2 2 0 2 1 1 2]
[1 0 2 0 1 1 0 2 3 2]
[0 0 1 0 3 0 0 2 2 3]
[3 2 2 1 2 1 3 1 0 1]
[1 1 2 1 0 0 0 0 0 2]
[0 2 0 0 1 0 0 1 0 0]
[0 2 0 0 1 0 0 0 0 1]
[0 0 0 1 0 0 1 2 1 0]
[2 0 1 3 0 0 2 0 2 3]
[0 2 1 0 0 0 2 0 3 0]
[1 0 1 0 1 2 0 0 0 1]
[0 1 0 2 2 1 2 0 0 1]
[2 0 0 1 2 0 0 2 0 0]
[0 1 0 1 0 0 1 1 2 2]
[3 0 2 1 0 0 1 1 0 0]
[0 0 1 2 3 0 0 4 2 2]
[2 0 0 1 0 1 1 1 1 0]
[2 0 1 2 0 0 0 2 0 2]
[1 0 0 0 2 0 1 0 0 1]
[0 0 1 0 3 0 0 1 0 2]
[0 1 1 1 1 1 1 1 3 1]
[0 0 3 0 1 0 1 0 1 2]
[1 2 1 0 1 1 0 1 2 1]
[1 0 1 0 2

[0 0 0 1 1 0 1 2 0 2]
[0 0 0 0 3 1 0 0 0 0]
[2 0 1 0 0 1 1 0 2 0]
[0 2 1 2 1 3 1 2 0 0]
[2 2 3 2 1 0 1 2 0 1]
[0 2 4 0 1 0 0 1 1 1]
[1 1 0 3 0 0 0 1 3 1]
[2 0 2 3 0 0 0 0 1 1]
[2 0 0 2 1 1 0 0 2 0]
[3 0 0 2 0 1 2 0 0 0]
[0 2 0 3 1 1 2 1 1 2]
[1 0 0 1 2 1 0 1 0 0]
[0 2 2 4 1 4 2 3 1 0]
[1 1 2 1 1 1 0 0 0 2]
[1 0 0 1 1 0 1 2 3 1]
[0 0 0 3 1 0 2 1 3 0]
[2 0 0 0 1 2 1 2 1 1]
[1 0 1 2 2 3 0 2 1 1]
[0 1 2 0 1 0 0 3 0 1]
[1 0 2 0 3 2 2 1 0 1]
[0 0 2 1 2 0 2 0 0 2]
[2 0 2 1 0 1 1 0 0 0]
[1 0 0 2 1 1 0 1 2 1]
[0 0 4 0 4 0 2 2 0 2]
[3 0 0 2 1 3 2 1 0 0]
[1 1 0 2 0 0 0 0 2 1]
[0 0 0 0 1 1 1 3 1 0]
[3 2 3 0 0 0 1 3 1 0]
[0 1 2 2 1 0 0 1 2 1]
[2 1 0 4 0 0 2 0 2 0]
[1 0 1 2 1 3 2 0 1 1]
[1 1 0 1 1 2 1 1 0 0]
[1 0 2 0 1 2 0 2 0 1]
[1 1 0 0 0 0 0 2 1 1]
[0 0 1 0 1 0 0 3 0 1]
[2 1 1 1 0 0 2 2 0 3]
[0 0 0 1 0 2 2 2 2 0]
[2 1 2 1 0 2 0 1 0 0]
[1 0 0 3 1 0 1 2 0 1]
[0 2 2 0 0 2 0 1 1 0]
[0 0 0 1 0 0 0 0 0 1]
[1 0 1 2 0 0 0 0 0 2]
[0 0 0 0 1 3 0 0 0 1]
[0 0 2 0 1 0 0 1 1 0]
[0 2 2 2 1 2 0 0 0 2]
[1 1 1 0 1

[2 0 0 1 0 2 0 2 2 1]
[0 1 0 1 2 0 2 2 0 0]
[2 1 2 0 0 0 0 2 0 0]
[2 3 2 0 0 3 0 0 0 3]
[0 3 2 3 0 0 0 3 4 3]
[0 0 0 0 1 0 0 1 2 2]
[2 1 0 1 1 0 0 0 0 1]
[2 0 0 1 0 1 1 1 0 1]
[0 0 1 0 0 1 0 0 0 2]
[1 3 1 1 2 2 0 0 0 0]
[0 0 0 2 0 0 0 1 3 1]
[1 0 2 0 0 2 1 2 1 0]
[1 1 2 2 0 1 1 0 0 0]
[0 0 1 3 1 1 0 2 1 1]
[2 0 0 1 1 3 1 3 1 0]
[3 3 3 0 1 1 2 1 1 2]
[3 3 0 1 0 1 0 0 0 1]
[1 0 2 3 0 2 2 0 0 0]
[0 2 1 1 0 2 0 0 0 1]
[1 0 2 0 1 2 1 3 0 0]
[1 0 2 1 2 1 1 2 2 0]
[2 1 0 1 2 0 2 1 0 0]
[1 0 0 3 1 2 0 0 0 0]
[1 0 2 0 2 0 1 0 0 1]
[0 1 0 0 1 1 3 1 2 0]
[2 2 0 2 0 1 0 0 0 1]
[2 0 1 1 0 2 1 0 0 2]
[1 0 1 0 0 0 0 0 2 0]
[0 1 2 1 1 1 0 0 0 2]
[0 3 1 0 0 0 0 0 0 2]
[3 1 2 1 0 1 1 1 0 0]
[0 0 2 0 2 1 0 2 2 2]
[1 0 2 1 0 0 1 2 2 0]
[1 2 0 0 2 2 0 0 1 0]
[0 2 1 0 3 0 0 2 1 2]
[4 2 0 0 1 1 0 1 0 1]
[0 1 0 1 0 1 2 1 0 2]
[1 0 3 1 0 0 0 0 1 0]
[3 2 1 1 0 0 0 0 2 3]
[1 3 1 0 0 1 2 1 2 0]
[0 2 0 2 0 1 1 0 0 0]
[0 0 0 0 3 0 1 3 1 2]
[1 0 0 0 0 0 1 0 3 2]
[2 1 0 1 1 1 1 0 1 0]
[1 0 0 3 1 0 1 2 3 3]
[3 1 0 0 2

[1 0 0 0 1 0 2 1 1 2]
[3 0 3 3 0 0 0 1 0 0]
[0 0 0 0 0 2 1 0 0 1]
[2 0 0 0 0 3 0 0 2 0]
[0 1 1 0 0 2 1 1 0 0]
[2 0 2 2 1 2 0 1 2 2]
[1 1 1 1 1 0 0 0 0 0]
[0 0 3 2 2 2 0 3 2 0]
[3 0 0 2 1 1 2 1 0 2]
[0 1 1 0 1 0 1 2 0 0]
[0 0 0 1 3 0 2 1 1 0]
[3 3 1 2 1 1 0 0 1 1]
[0 0 1 0 0 1 2 3 0 1]
[2 0 3 3 0 2 0 2 0 2]
[2 0 0 2 0 0 0 1 0 2]
[2 0 3 2 0 1 0 2 0 2]
[2 1 1 1 1 1 0 0 2 2]
[0 0 2 1 0 0 0 1 0 0]
[1 1 3 3 0 1 1 3 0 0]
[0 4 1 1 3 2 0 2 2 0]
[0 0 0 3 4 1 0 2 0 1]
[0 1 2 3 2 1 1 1 3 0]
[3 0 2 0 0 1 1 1 0 1]
[0 2 1 0 1 0 0 1 2 2]
[0 1 1 0 3 0 1 0 0 1]
[1 3 0 2 2 1 2 2 1 2]
[1 1 2 2 0 1 0 1 1 0]
[1 1 2 0 0 1 0 0 0 1]
[0 0 0 0 0 0 1 0 1 3]
[2 0 0 0 0 4 0 0 0 1]
[1 0 0 1 3 0 1 3 0 2]
[1 1 0 0 0 2 1 0 0 2]
[0 0 3 1 0 2 1 0 0 1]
[2 0 0 1 1 1 2 0 3 1]
[0 1 0 2 4 1 0 0 1 1]
[3 1 1 1 1 1 1 0 0 0]
[1 0 0 1 1 2 0 2 2 0]
[0 1 2 0 3 0 1 2 0 0]
[0 1 2 0 1 2 2 2 3 1]
[3 0 0 0 0 1 1 0 0 0]
[0 1 0 0 2 0 2 1 1 3]
[0 1 2 3 4 2 2 1 0 0]
[1 0 0 1 0 3 4 3 0 1]
[0 2 2 0 0 1 0 0 3 0]
[1 0 0 0 0 0 1 1 1 2]
[3 0 0 0 0

[1 2 3 2 0 1 0 1 0 1]
[1 1 0 1 3 0 3 0 1 0]
[0 4 0 3 2 0 3 1 0 0]
[2 2 1 0 0 1 2 1 0 0]
[0 0 0 0 1 2 0 0 3 1]
[1 0 2 3 0 1 0 0 2 0]
[0 2 2 0 2 0 0 0 2 1]
[3 1 0 1 3 0 0 2 0 0]
[0 0 1 3 0 2 0 0 2 1]
[1 2 1 2 1 3 0 1 1 0]
[1 0 0 2 4 1 0 1 1 0]
[2 0 1 0 1 2 0 1 1 0]
[0 0 1 0 0 3 3 2 0 2]
[1 3 1 0 2 0 1 2 0 2]
[1 0 1 0 0 1 0 0 0 2]
[2 0 2 1 2 1 3 2 1 1]
[1 3 1 2 1 2 1 0 0 0]
[0 3 0 2 0 0 2 0 1 2]
[0 2 0 2 1 0 0 1 1 0]
[0 1 2 0 1 0 2 0 0 1]
[0 2 0 1 2 0 0 0 0 0]
[0 1 2 2 3 1 1 2 1 0]
[2 0 0 4 0 0 0 0 1 3]
[3 1 3 0 0 1 2 0 1 0]
[0 3 1 0 1 1 1 1 0 0]
[0 2 0 2 0 1 0 0 0 0]
[1 0 0 0 0 1 1 0 0 1]
[1 1 0 2 1 1 1 1 0 2]
[2 0 2 0 0 1 1 2 0 1]
[2 0 1 0 1 0 0 0 0 1]
[0 2 1 0 0 2 0 0 1 0]
[2 0 2 0 2 2 2 3 0 1]
[0 0 0 0 0 0 0 2 0 1]
[0 1 0 0 0 0 0 0 0 2]
[2 2 1 1 0 1 1 0 1 0]
[0 0 1 0 0 1 0 0 0 2]
[0 0 1 0 1 0 1 0 1 0]
[0 1 2 1 0 0 1 1 2 0]
[2 0 1 0 1 2 1 0 2 0]
[0 0 3 1 0 0 1 0 0 0]
[0 2 2 2 0 2 0 1 0 1]
[2 0 2 1 0 3 0 1 2 0]
[0 3 0 3 3 0 1 2 0 1]
[2 2 0 2 0 1 0 0 2 2]
[0 0 1 0 3 0 2 2 0 1]
[2 0 0 1 3

[0 1 0 1 0 4 0 0 0 1]
[4 1 4 0 0 0 1 1 2 0]
[0 1 0 0 2 0 2 0 1 1]
[0 0 0 0 1 1 0 0 0 2]
[2 2 0 2 2 2 2 1 1 0]
[0 0 1 1 0 1 0 0 2 1]
[2 3 0 1 3 0 2 0 2 2]
[0 1 2 0 0 0 1 2 1 0]
[2 1 0 2 0 0 0 0 2 1]
[0 0 2 2 2 1 1 1 1 1]
[0 2 0 1 1 0 2 2 0 0]
[2 0 1 0 1 1 0 0 0 0]
[2 0 2 2 2 2 0 0 2 1]
[2 2 1 0 0 0 1 0 2 2]
[0 0 4 1 0 2 2 2 2 0]
[0 0 2 0 0 0 0 0 1 1]
[3 4 1 0 0 0 1 2 1 0]
[2 1 0 3 0 2 0 0 1 2]
[1 2 3 3 0 1 2 0 3 0]
[1 0 0 0 0 0 0 2 0 1]
[0 0 1 0 1 3 3 1 1 1]
[0 1 0 1 0 0 2 1 1 0]
[0 0 1 2 0 3 1 0 0 0]
[0 3 0 0 2 0 2 0 2 2]
[3 0 0 0 1 0 2 0 0 4]
[2 1 2 0 0 0 0 0 0 0]
[1 3 1 0 0 2 2 0 1 1]
[0 2 1 0 0 0 4 0 0 1]
[3 0 2 1 0 3 0 2 2 0]
[0 0 2 0 1 0 1 1 0 1]
[0 1 1 0 1 1 1 3 0 1]
[2 1 2 0 1 0 1 1 0 1]
[2 0 3 1 0 0 2 2 1 1]
[0 0 0 2 0 0 0 2 0 1]
[1 2 0 2 0 2 2 3 2 0]
[0 2 2 3 3 1 0 1 1 2]
[2 2 2 1 2 1 0 2 2 1]
[3 3 1 0 0 0 0 2 0 0]
[1 0 2 0 0 2 0 1 3 0]
[0 1 0 0 4 0 2 2 0 1]
[0 0 2 0 0 1 0 0 0 1]
[0 0 0 0 1 0 0 1 0 0]
[0 1 0 1 2 1 0 0 1 1]
[1 2 2 2 2 0 0 2 0 0]
[3 2 0 2 1 0 3 1 2 2]
[0 1 0 0 0

[0 2 1 1 0 0 2 0 0 2]
[0 2 0 1 2 1 0 1 1 1]
[0 0 1 0 2 2 0 1 1 0]
[2 0 4 0 1 0 0 2 1 0]
[0 1 4 0 3 0 1 0 0 0]
[0 1 3 1 0 0 0 0 1 0]
[1 2 0 0 1 0 0 0 0 1]
[0 0 1 1 0 0 0 0 0 2]
[1 1 0 0 0 0 1 1 2 1]
[2 2 2 1 0 0 0 2 0 0]
[1 0 1 0 2 0 1 1 1 0]
[0 1 0 2 1 0 0 0 0 1]
[1 0 1 0 4 1 3 1 2 0]
[3 2 0 0 0 0 2 1 1 0]
[1 2 0 0 1 2 0 0 0 0]
[3 1 1 0 0 0 0 0 3 2]
[0 2 1 0 0 2 0 2 0 2]
[0 3 1 0 0 1 2 1 2 0]
[1 1 2 0 1 0 0 0 1 0]
[1 0 1 0 0 1 3 0 2 0]
[0 1 0 2 1 0 0 0 0 0]
[1 0 2 2 1 1 2 1 1 0]
[2 1 1 0 1 1 3 1 0 0]
[1 2 2 1 1 3 0 0 0 2]
[0 2 0 0 2 1 0 0 0 0]
[1 1 1 2 1 1 2 4 0 0]
[2 1 2 0 0 1 0 3 1 1]
[0 3 1 0 0 0 0 2 2 0]
[1 0 0 0 0 1 1 2 0 0]
[2 0 0 2 0 2 0 3 0 0]
[0 1 0 0 0 3 2 3 0 0]
[4 1 0 2 0 1 2 1 2 1]
[2 0 2 0 1 1 1 0 2 0]
[1 0 1 0 0 0 1 1 1 2]
[2 0 0 0 2 0 3 2 1 1]
[1 3 3 1 1 0 1 0 1 1]
[0 1 1 1 0 0 2 1 2 0]
[1 1 0 1 1 2 0 1 2 0]
[0 1 0 2 3 1 1 0 2 1]
[0 2 3 0 2 2 0 2 1 0]
[1 0 1 0 0 3 0 1 1 2]
[2 0 0 0 0 0 0 0 1 0]
[3 0 0 0 1 0 1 2 2 0]
[3 1 0 0 2 3 0 1 0 0]
[3 0 0 1 0 2 1 1 1 1]
[0 0 0 1 3

[3 0 4 1 0 2 1 0 1 1]
[1 0 0 3 2 2 0 0 2 1]
[0 0 1 0 4 2 0 0 0 1]
[1 1 2 1 0 1 1 0 2 1]
[1 2 0 2 0 1 0 0 3 3]
[2 1 0 3 2 1 0 0 1 2]
[0 0 0 0 1 0 0 0 1 2]
[0 0 2 0 1 1 0 4 0 1]
[4 2 1 0 0 0 0 1 1 0]
[0 0 0 0 1 3 3 2 2 0]
[0 1 0 0 1 2 0 1 2 2]
[1 1 1 0 0 2 2 0 1 0]
[2 3 0 1 0 1 0 2 2 0]
[1 0 2 0 4 3 1 2 2 2]
[0 1 0 1 2 2 0 3 3 0]
[1 1 2 1 4 2 0 2 3 1]
[0 2 0 2 0 0 2 0 4 1]
[0 0 3 2 1 0 2 2 0 3]
[1 3 3 0 0 0 1 2 0 0]
[2 0 0 1 2 2 0 2 1 1]
[4 1 2 0 0 0 0 2 2 1]
[0 0 0 1 0 0 2 0 0 0]
[0 1 0 1 1 0 0 0 1 2]
[0 1 0 1 2 2 0 2 0 1]
[0 0 3 0 1 0 1 4 0 0]
[2 3 0 0 0 1 1 1 2 1]
[0 0 2 1 2 0 0 2 1 2]
[3 2 0 1 0 1 3 0 1 0]
[2 1 2 0 2 1 1 0 2 2]
[3 1 1 2 0 0 3 0 0 0]
[0 2 0 0 0 0 1 0 2 0]
[0 1 0 1 0 0 0 3 1 2]
[0 0 1 1 3 3 1 0 0 3]
[2 0 0 3 0 0 2 0 0 1]
[0 2 2 1 1 3 0 1 0 0]
[2 0 3 0 1 0 1 2 2 0]
[0 0 1 0 1 0 0 0 0 0]
[0 1 0 1 0 2 0 0 0 2]
[0 3 0 1 3 2 0 0 0 0]
[0 0 1 1 0 2 2 0 3 1]
[2 0 2 0 2 0 0 0 2 2]
[1 2 0 1 0 3 0 1 1 1]
[1 0 1 0 0 3 1 0 1 1]
[1 0 1 3 0 1 0 0 0 0]
[2 2 2 0 0 0 1 0 1 0]
[2 0 1 4 1

[1 2 0 3 1 2 0 1 2 0]
[0 2 2 0 0 0 2 1 1 0]
[1 0 0 1 0 1 2 0 1 1]
[2 0 0 0 1 3 2 0 2 0]
[0 0 0 0 0 0 1 2 0 0]
[0 2 1 2 2 3 1 0 2 1]
[2 0 2 2 1 0 3 0 1 0]
[0 0 0 0 0 0 0 0 0 0]
[1 2 1 3 0 0 0 1 0 1]
[0 1 0 0 0 1 0 2 0 1]
[1 1 0 2 2 2 2 1 2 1]
[3 0 0 0 2 3 1 1 2 0]
[1 0 0 0 3 2 1 0 2 2]
[0 2 1 1 3 3 0 4 3 2]
[3 1 2 0 0 0 0 0 2 0]
[0 0 1 3 2 1 0 3 1 1]
[0 1 2 2 1 2 2 1 0 0]
[1 0 1 1 1 0 2 0 2 2]
[0 0 2 2 0 1 0 0 1 1]
[1 1 0 1 3 0 3 0 1 4]
[0 0 0 1 0 1 3 0 0 2]
[2 0 3 0 0 0 2 1 2 1]
[2 0 0 1 1 0 1 0 4 1]
[3 2 0 0 0 1 2 0 2 0]
[1 2 3 0 1 0 0 1 2 0]
[0 0 3 0 2 1 0 1 0 0]
[0 1 1 2 0 0 0 2 0 3]
[2 0 0 1 2 1 0 2 2 1]
[0 1 0 2 2 1 0 0 0 2]
[0 0 1 2 0 2 0 0 1 0]
[2 1 1 0 0 0 2 0 0 0]
[2 0 0 0 0 0 2 2 0 0]
[0 2 2 1 0 0 3 0 0 3]
[0 2 2 1 2 0 0 1 0 1]
[2 1 2 1 0 0 0 2 1 0]
[1 4 2 1 1 0 1 2 4 0]
[0 1 1 1 1 2 2 0 0 1]
[1 0 1 0 2 2 1 0 2 2]
[0 0 0 1 2 1 2 0 2 1]
[0 0 1 3 1 0 0 1 0 1]
[3 2 1 3 2 2 2 0 1 0]
[0 2 2 0 0 0 1 0 0 1]
[1 3 1 2 1 0 0 0 2 0]
[1 2 2 0 0 0 0 2 0 1]
[0 0 1 1 0 1 0 1 3 0]
[0 0 2 2 0

[1 1 0 0 0 0 0 0 1 0]
[1 2 3 1 0 0 0 0 2 2]
[2 1 0 1 2 2 0 2 1 1]
[3 2 1 2 0 1 2 1 1 0]
[2 1 0 0 0 0 0 2 0 1]
[1 0 2 2 0 2 0 0 1 0]
[0 0 4 0 2 0 0 0 0 0]
[0 2 0 2 1 0 0 0 2 0]
[3 2 0 1 0 0 1 1 0 1]
[1 0 1 2 0 0 1 1 0 3]
[0 2 0 3 0 2 0 0 0 1]
[1 0 1 0 0 0 1 2 2 0]
[1 1 0 0 3 1 2 4 1 0]
[0 1 0 0 0 0 0 0 0 0]
[2 1 0 0 0 0 1 0 0 1]
[0 2 1 4 3 4 0 1 2 2]
[1 2 0 0 2 0 1 0 0 0]
[3 1 0 0 0 0 1 0 2 1]
[3 0 0 0 0 0 1 2 0 0]
[0 2 3 2 0 0 2 1 0 0]
[1 1 0 0 1 0 2 0 1 0]
[0 0 1 1 4 4 2 2 1 2]
[0 1 0 3 2 1 0 0 2 0]
[2 1 0 1 0 2 1 0 1 1]
[0 2 3 1 0 3 0 2 0 1]
[1 1 1 1 1 1 0 0 0 2]
[1 1 0 2 0 0 0 1 1 0]
[1 2 0 0 2 3 0 1 0 0]
[0 1 2 1 0 0 2 0 0 2]
[1 1 1 0 0 2 1 0 0 1]
[2 0 0 0 2 0 1 0 0 3]
[2 1 0 3 0 0 2 0 2 4]
[0 0 0 2 2 2 0 0 0 1]
[2 0 0 0 2 2 4 2 1 2]
[1 1 0 1 1 0 1 3 0 1]
[1 0 0 3 1 2 0 0 2 2]
[2 1 2 3 1 2 0 1 2 1]
[0 1 0 2 2 2 1 1 2 1]
[0 0 1 2 1 1 1 0 1 0]
[1 0 0 4 0 1 1 2 1 0]
[0 1 0 0 2 1 0 2 2 0]
[1 0 2 0 0 1 0 0 0 0]
[2 1 1 4 1 0 0 0 2 0]
[0 0 2 0 2 1 2 0 0 1]
[0 2 3 0 0 0 0 3 2 0]
[0 3 0 1 1

[1 2 0 0 1 2 0 0 1 2]
[3 3 1 1 4 1 1 0 0 1]
[0 2 0 0 0 0 2 0 1 1]
[0 1 0 2 1 2 2 0 0 0]
[0 3 0 1 0 2 0 1 1 0]
[0 0 0 0 2 1 0 2 0 2]
[0 0 0 0 0 0 0 0 1 0]
[0 0 1 2 1 0 0 3 0 1]
[0 0 1 1 0 0 1 1 0 0]
[0 0 1 0 0 2 1 2 0 0]
[2 0 2 1 1 1 2 1 2 0]
[0 0 0 3 0 0 0 0 1 2]
[2 1 3 0 0 0 3 0 1 0]
[1 0 2 0 0 0 1 0 2 0]
[2 0 0 0 0 0 3 1 0 2]
[0 1 2 1 2 1 2 0 1 0]
[2 1 1 1 0 0 1 3 1 2]
[0 4 2 0 1 2 1 3 1 0]
[3 0 0 2 1 2 0 0 3 2]
[0 0 0 0 0 1 0 1 0 2]
[0 2 1 1 1 2 1 2 1 2]
[2 0 1 1 3 0 2 2 0 0]
[2 2 0 0 0 0 0 1 0 0]
[1 0 0 0 1 0 0 0 2 0]
[0 1 0 1 0 0 3 1 2 1]
[1 0 1 1 0 0 0 1 0 3]
[0 0 2 1 0 0 0 0 0 2]
[0 1 1 4 1 0 3 4 0 1]
[2 1 0 1 1 0 0 0 1 0]
[0 2 1 0 0 1 2 0 1 0]
[2 0 0 0 1 0 2 2 1 2]
[2 2 1 0 0 0 2 1 1 1]
[0 3 0 4 0 1 1 0 1 1]
[0 0 1 1 1 1 0 1 2 0]
[2 0 0 2 0 2 1 0 0 1]
[0 2 2 1 0 3 0 0 0 0]
[1 0 0 2 2 0 1 2 1 0]
[1 0 2 0 1 0 0 1 0 0]
[0 1 1 1 0 1 0 0 1 0]
[0 1 1 1 2 0 3 0 0 0]
[0 0 0 0 1 0 2 1 0 1]
[2 4 1 1 2 1 0 2 2 1]
[0 0 0 0 0 2 3 1 0 0]
[0 0 0 2 1 0 1 0 1 2]
[1 0 2 4 0 0 3 0 0 1]
[1 1 0 1 3

[1 0 0 3 1 1 2 1 0 0]
[0 3 2 2 0 4 2 1 1 0]
[4 2 0 0 2 0 0 2 3 3]
[1 1 1 0 1 1 1 0 0 1]
[1 0 1 0 2 2 1 0 1 2]
[1 0 0 0 0 1 0 0 2 0]
[1 0 2 0 0 0 0 1 0 0]
[2 3 0 0 1 0 0 0 3 0]
[3 2 0 1 1 1 1 1 1 1]
[1 1 0 0 1 0 0 3 3 1]
[1 1 1 0 1 1 0 1 1 0]
[1 1 2 0 0 1 0 1 0 1]
[1 0 0 2 2 0 0 2 0 1]
[0 1 2 0 0 0 0 3 1 1]
[2 4 2 1 0 0 0 0 3 0]
[2 0 0 1 2 0 2 1 0 4]
[0 0 2 0 3 0 2 4 3 0]
[1 0 1 0 2 0 0 0 0 1]
[1 1 1 1 1 2 1 0 1 1]
[0 0 3 1 0 1 2 0 0 0]
[0 1 0 1 0 1 0 0 2 1]
[0 1 0 0 0 0 1 2 3 0]
[0 0 0 0 1 0 1 0 1 0]
[1 1 0 2 2 1 0 0 1 0]
[2 0 0 1 1 1 0 0 1 1]
[1 3 0 1 0 0 0 1 2 0]
[1 1 3 1 1 1 0 0 1 1]
[3 0 2 0 3 0 0 0 2 0]
[0 1 0 4 0 2 4 2 0 1]
[0 0 0 0 1 2 0 0 0 0]
[2 1 2 0 0 3 0 3 0 0]
[0 1 0 1 1 0 0 1 2 0]
[1 0 3 0 2 2 0 2 0 0]
[0 2 2 0 1 2 2 4 0 0]
[1 1 2 0 0 1 2 1 1 2]
[4 0 0 2 1 1 1 1 0 0]
[0 3 0 2 0 0 1 1 1 0]
[2 2 0 0 0 3 3 0 1 1]
[0 2 3 1 1 0 1 0 0 2]
[0 0 1 2 2 2 1 1 3 0]
[4 1 0 2 1 2 0 0 2 0]
[0 0 3 2 0 0 2 2 0 0]
[0 1 1 0 0 0 2 1 0 2]
[0 2 2 0 0 1 0 1 0 1]
[0 2 0 0 0 2 2 0 1 0]
[2 1 3 0 0

[2 2 2 1 2 2 0 0 0 1]
[1 0 0 0 2 0 0 0 0 4]
[2 2 3 1 1 0 0 2 1 0]
[3 0 1 0 2 0 0 1 1 0]
[1 0 0 2 0 2 1 0 0 0]
[1 0 1 1 1 1 1 0 2 0]
[1 1 3 1 0 0 0 0 1 0]
[1 0 0 0 1 1 0 0 0 0]
[1 2 0 0 0 2 0 1 1 2]
[2 2 0 2 2 2 1 0 0 0]
[0 0 0 1 1 0 3 0 0 1]
[1 0 0 0 1 0 2 1 1 2]
[2 2 0 2 0 1 2 0 3 0]
[2 0 0 0 0 0 2 1 1 0]
[0 0 0 2 1 1 0 0 2 0]
[0 0 2 0 0 2 0 2 0 1]
[1 0 1 1 0 1 0 2 0 0]
[1 0 1 2 2 0 0 0 1 1]
[3 1 2 1 1 0 2 0 2 0]
[1 0 1 1 4 3 3 0 0 1]
[2 2 1 2 3 0 0 0 1 0]
[0 0 0 0 1 2 0 3 0 0]
[0 1 1 1 0 1 0 2 0 1]
[0 0 0 1 1 0 0 2 0 0]
[1 1 0 3 1 0 0 0 0 2]
[0 0 1 0 0 1 3 2 1 1]
[2 0 1 2 2 3 0 0 2 1]
[0 0 2 1 1 1 2 1 3 1]
[2 0 2 0 2 0 0 1 0 1]
[0 1 0 0 0 0 0 0 2 2]
[2 3 1 0 1 2 0 1 0 1]
[0 0 1 0 1 1 0 2 0 1]
[0 3 1 1 0 0 0 2 1 1]
[0 1 0 2 0 2 1 2 1 0]
[2 0 2 1 2 1 0 0 2 1]
[0 1 1 0 0 0 0 0 1 0]
[0 1 2 0 3 0 0 0 1 1]
[0 2 0 0 0 0 0 3 0 3]
[2 2 0 1 2 0 0 1 0 1]
[2 2 0 0 2 2 0 1 0 2]
[0 1 0 1 2 0 1 1 1 2]
[3 0 0 1 1 3 0 0 1 3]
[3 3 0 0 2 1 0 2 1 1]
[0 0 3 0 2 1 1 1 0 1]
[0 1 2 0 0 1 3 3 1 1]
[0 0 1 0 2

[1 3 1 0 1 1 0 1 3 0]
[0 2 3 0 0 0 2 0 2 0]
[1 0 1 1 0 0 1 0 2 2]
[1 1 0 0 2 0 1 0 3 1]
[1 0 1 0 2 2 0 1 0 1]
[0 3 0 1 2 2 2 1 0 1]
[0 0 0 1 0 0 2 1 0 0]
[2 0 1 0 4 2 0 1 0 1]
[2 2 0 2 1 1 0 0 3 0]
[0 0 1 0 2 1 1 3 0 0]
[1 2 2 0 0 1 1 1 0 0]
[2 0 1 0 0 0 0 0 0 3]
[0 2 1 1 0 0 0 1 2 0]
[0 4 0 0 3 2 3 1 0 1]
[1 0 1 0 0 1 1 2 1 2]
[0 0 2 0 0 1 0 1 0 1]
[1 0 0 2 0 1 0 0 1 0]
[0 2 0 0 0 3 0 0 1 1]
[2 2 0 0 0 1 2 0 0 0]
[0 0 1 1 0 0 1 2 0 2]
[0 0 0 1 3 2 2 0 2 1]
[1 0 0 0 1 2 0 0 0 0]
[2 2 0 0 1 1 1 2 0 1]
[0 0 2 3 0 1 1 1 2 0]
[0 0 0 0 0 0 2 0 0 1]
[1 0 1 1 0 3 0 1 0 0]
[2 1 0 1 0 3 1 1 1 0]
[0 2 1 2 0 0 0 0 1 0]
[0 0 1 1 2 1 1 2 0 0]
[0 1 0 0 1 0 0 2 0 0]
[0 0 0 0 2 1 0 2 3 0]
[0 1 2 0 0 3 1 2 1 1]
[0 1 0 0 0 1 1 0 1 2]
[3 2 4 0 0 1 0 3 1 1]
[0 4 1 0 0 0 2 0 0 1]
[1 0 0 1 1 1 0 0 2 2]
[4 1 0 1 2 1 0 0 2 0]
[0 0 0 0 1 0 2 2 3 0]
[1 0 1 2 2 2 0 3 1 0]
[2 1 0 1 0 2 0 0 1 0]
[1 0 1 1 0 1 0 1 1 3]
[0 1 2 0 0 3 0 0 1 1]
[1 2 2 2 4 2 0 2 0 1]
[0 1 0 2 2 2 1 0 0 0]
[2 0 0 0 1 0 2 0 0 0]
[2 2 1 0 0

[1 0 0 1 0 2 3 0 1 2]
[1 1 1 2 1 0 1 2 3 0]
[2 1 1 1 0 0 0 3 1 1]
[0 1 0 0 0 0 3 2 1 0]
[1 0 2 0 0 1 0 1 0 3]
[0 0 0 0 0 0 1 1 0 2]
[2 2 1 1 3 1 2 3 2 1]
[0 2 0 2 1 3 1 1 0 2]
[2 2 0 0 0 1 1 0 2 1]
[1 0 1 0 3 1 0 0 0 4]
[0 0 1 1 0 3 1 1 1 1]
[3 2 1 0 0 1 1 1 1 0]
[1 2 1 1 0 0 0 1 1 1]
[0 0 2 1 2 1 2 2 0 2]
[0 0 1 1 2 1 1 0 0 0]
[1 2 0 0 0 0 1 1 0 0]
[0 1 2 0 0 1 1 1 0 3]
[0 0 0 3 3 2 0 1 1 1]
[0 0 2 2 0 0 0 0 1 0]
[2 3 0 0 2 0 3 1 0 2]
[0 0 0 1 2 1 1 1 3 2]
[2 0 0 0 1 0 0 1 0 0]
[2 1 2 0 3 2 3 0 0 0]
[1 3 0 0 1 0 0 0 1 1]
[0 1 0 0 0 0 0 1 3 1]
[0 0 1 0 0 0 1 1 0 0]
[0 0 2 2 1 0 0 1 2 2]
[2 2 2 1 1 1 1 1 0 1]
[2 2 0 0 4 1 0 0 2 2]
[0 1 0 2 0 1 2 0 0 0]
[1 0 0 1 1 2 0 1 1 0]
[1 1 0 0 2 2 2 0 0 1]
[0 4 0 0 1 1 1 1 1 2]
[2 0 3 1 3 3 0 0 0 1]
[0 0 0 2 0 3 0 0 1 2]
[2 2 1 1 1 0 0 1 2 0]
[0 2 3 1 0 3 0 1 0 0]
[1 0 0 3 0 0 0 1 0 0]
[0 1 1 0 2 1 0 0 1 2]
[0 0 0 3 2 0 3 1 1 2]
[0 0 1 0 0 1 1 0 0 0]
[3 2 0 0 1 0 2 0 1 2]
[1 0 0 1 0 0 0 1 0 2]
[0 1 0 3 2 0 3 0 1 0]
[2 2 0 1 2 0 1 1 1 0]
[0 0 0 0 0

[2 1 0 0 1 2 0 2 1 1]
[2 1 2 2 1 2 0 0 0 0]
[1 0 2 0 0 0 2 3 2 0]
[3 0 0 0 0 0 1 1 2 0]
[2 0 2 2 2 1 1 0 0 1]
[2 1 0 0 0 0 1 2 0 2]
[0 2 1 0 0 1 0 1 2 0]
[0 1 0 2 1 1 2 0 0 2]
[2 1 1 0 0 1 1 0 0 0]
[1 1 0 0 2 2 1 0 2 2]
[1 1 0 2 2 0 0 0 1 0]
[1 1 2 1 3 1 1 0 0 0]
[2 1 4 0 2 0 0 1 2 0]
[0 1 0 3 0 1 2 3 1 0]
[2 2 0 2 2 0 1 0 1 1]
[0 1 1 0 3 0 0 4 2 1]
[0 0 2 0 0 2 0 1 2 1]
[2 2 0 0 0 3 0 0 0 2]
[1 1 2 1 0 0 0 1 1 2]
[0 2 0 0 0 1 1 2 3 1]
[2 0 1 0 0 1 1 0 0 0]
[3 0 0 2 3 1 0 0 2 1]
[0 2 0 0 0 0 3 0 0 0]
[3 0 1 2 1 0 0 0 2 3]
[0 2 0 2 3 0 2 4 0 2]
[0 0 0 1 2 1 0 0 1 1]
[3 1 1 0 1 0 0 2 2 1]
[1 0 2 0 1 2 0 0 0 0]
[0 1 0 1 0 1 2 1 0 0]
[0 0 0 1 0 1 0 1 2 0]
[2 1 1 1 1 0 0 4 0 0]
[2 2 0 0 0 0 1 0 2 0]
[1 1 1 2 1 2 0 0 1 2]
[1 0 0 0 0 1 0 2 2 1]
[0 2 1 3 0 3 1 1 1 2]
[0 0 1 0 3 1 2 2 0 0]
[0 2 1 1 2 0 2 3 1 1]
[1 2 3 2 1 0 1 2 0 0]
[1 0 0 2 3 0 2 0 0 0]
[0 0 1 1 3 3 1 2 0 1]
[0 2 1 0 1 1 0 0 1 0]
[0 1 0 0 0 0 1 0 0 1]
[0 0 1 0 2 1 0 0 0 0]
[3 0 2 1 2 0 0 0 0 0]
[1 3 1 0 1 3 0 2 0 0]
[1 0 0 0 2

[0 0 2 0 0 4 1 2 0 0]
[2 1 2 0 0 0 1 0 1 1]
[1 3 1 0 1 1 0 0 0 2]
[0 0 1 0 2 3 1 2 0 0]
[3 1 3 2 0 1 0 0 1 1]
[0 0 2 0 1 1 1 0 0 1]
[1 1 2 1 1 1 1 0 0 0]
[0 1 1 0 0 2 3 1 1 2]
[1 4 0 2 0 1 1 4 2 0]
[3 1 1 2 0 2 0 0 0 0]
[0 1 1 4 0 1 0 2 0 2]
[2 2 0 2 2 0 2 0 0 0]
[0 1 0 0 0 2 1 2 2 0]
[1 0 0 0 0 0 0 3 2 0]
[2 0 0 0 3 2 1 1 1 0]
[0 1 0 0 2 1 1 1 2 0]
[0 0 2 0 3 2 0 0 1 0]
[0 0 0 2 2 2 0 0 1 3]
[0 0 0 1 0 1 2 0 2 1]
[2 1 0 2 0 1 3 0 1 1]
[0 2 2 1 0 1 0 0 1 2]
[1 0 2 3 0 0 0 2 0 2]
[1 0 2 1 0 0 0 0 0 2]
[0 0 0 1 2 0 0 1 1 0]
[1 1 0 3 1 0 1 2 1 2]
[0 1 2 1 2 0 2 0 0 3]
[1 2 3 1 2 2 2 0 3 0]
[2 1 0 1 0 0 1 1 1 0]
[1 2 0 0 2 0 0 3 0 0]
[3 0 1 0 1 0 0 2 0 1]
[1 1 0 0 0 0 1 0 0 1]
[1 2 1 0 1 2 4 0 3 0]
[1 0 1 2 1 0 0 2 3 0]
[1 1 0 0 1 0 1 4 2 2]
[0 0 0 0 0 0 0 0 1 1]
[0 1 2 0 2 0 0 0 2 2]
[2 1 2 0 1 1 0 2 1 0]
[0 1 0 1 1 0 1 3 1 1]
[0 2 0 2 0 0 0 0 0 0]
[0 3 0 1 3 3 0 0 0 0]
[0 0 1 1 0 0 0 2 2 1]
[1 0 1 1 2 1 1 0 0 1]
[0 0 0 2 1 0 1 0 0 0]
[0 0 0 1 1 0 1 0 1 2]
[0 1 0 0 0 0 0 2 2 1]
[1 1 2 2 0

[0 1 0 0 1 2 1 0 1 0]
[0 3 0 1 0 0 1 1 2 1]
[2 0 0 0 0 0 0 0 2 0]
[0 0 2 0 0 0 2 0 0 2]
[0 0 0 0 1 0 1 0 2 2]
[2 1 0 2 4 0 0 0 0 1]
[3 1 1 0 0 0 2 0 2 1]
[0 1 1 2 1 0 1 4 0 0]
[0 1 1 3 0 0 1 0 2 1]
[2 0 1 0 3 1 0 3 2 1]
[0 3 0 0 0 2 3 2 0 0]
[2 3 0 1 0 2 2 0 1 1]
[0 0 2 1 2 2 1 1 2 2]
[0 1 2 0 0 0 0 1 0 0]
[0 1 0 1 0 0 1 1 0 1]
[1 2 0 1 0 0 1 2 3 0]
[1 1 0 0 0 0 2 0 1 1]
[1 1 0 1 0 0 0 0 0 3]
[1 2 2 1 0 3 0 1 2 2]
[1 1 0 0 0 2 0 0 0 0]
[0 0 1 2 0 0 2 0 0 1]
[0 1 1 2 0 0 0 0 0 1]
[0 0 0 1 1 1 0 1 3 2]
[0 0 2 0 0 0 0 1 1 0]
[0 0 2 0 2 1 1 0 2 1]
[0 1 0 1 1 1 1 2 0 2]
[3 1 0 0 0 0 2 0 3 1]
[2 1 0 0 2 2 0 2 1 0]
[0 1 1 0 0 0 0 0 1 1]
[0 3 0 1 0 0 0 3 0 0]
[3 0 1 1 0 0 1 0 0 1]
[2 2 0 0 1 0 1 1 0 1]
[0 1 2 0 0 0 0 0 0 2]
[0 1 2 0 1 2 4 0 0 2]
[1 0 2 0 2 0 3 3 0 0]
[1 0 0 0 0 1 1 2 1 0]
[0 0 0 1 3 0 1 2 0 0]
[1 0 2 1 0 0 2 1 0 1]
[0 2 2 1 4 2 0 1 0 2]
[1 2 0 0 2 1 0 1 0 0]
[1 2 1 2 0 0 1 0 2 0]
[0 0 0 1 1 0 2 0 0 2]
[0 2 0 1 2 0 3 1 0 0]
[1 0 2 2 0 1 0 1 2 1]
[3 0 2 1 2 0 0 1 2 3]
[0 0 1 0 3

[1 1 0 0 2 1 2 0 0 0]
[1 0 1 0 1 0 0 0 2 1]
[1 2 0 2 1 0 3 1 0 1]
[2 0 0 2 1 0 0 1 0 0]
[0 1 1 2 0 0 0 1 1 0]
[1 0 0 0 2 2 0 4 1 1]
[3 1 0 1 0 1 1 0 3 3]
[0 0 2 2 1 2 3 0 1 3]
[1 2 0 1 0 1 1 3 2 0]
[0 0 1 1 2 1 0 2 0 0]
[0 2 1 2 0 1 3 1 0 2]
[0 0 2 1 0 3 0 0 0 0]
[0 0 1 1 0 2 1 0 2 0]
[1 0 1 2 2 0 0 1 0 0]
[1 0 3 0 0 2 2 0 1 0]
[1 2 0 0 3 0 1 1 1 2]
[3 0 0 0 3 0 3 1 2 3]
[2 2 1 1 0 0 1 3 0 1]
[2 3 1 3 1 1 0 0 2 0]
[0 0 0 1 1 0 0 0 2 2]
[0 1 0 1 1 0 1 0 1 0]
[1 1 0 1 1 3 0 1 1 0]
[0 0 0 3 0 0 0 2 0 1]
[3 3 1 1 0 0 0 0 1 2]
[0 1 1 1 1 2 2 1 1 2]
[0 1 0 0 3 1 0 2 0 4]
[0 1 0 1 0 2 0 2 1 2]
[2 1 2 1 0 1 2 0 1 0]
[0 0 1 1 2 1 1 1 0 0]
[0 0 2 2 0 2 2 0 0 0]
[2 0 0 2 0 1 0 2 0 2]
[0 0 2 1 2 0 0 0 3 2]
[1 0 3 2 1 2 0 2 0 0]
[0 2 1 0 0 0 1 2 0 0]
[1 0 3 0 1 3 1 0 2 2]
[0 0 0 2 0 0 0 2 0 1]
[2 1 2 0 1 0 0 0 0 3]
[1 1 0 1 3 0 2 1 1 1]
[2 1 2 0 1 0 2 2 1 1]
[0 2 0 0 2 0 1 0 0 0]
[2 2 1 0 4 3 2 2 0 1]
[0 1 0 0 1 4 0 2 0 2]
[2 1 0 3 1 0 0 1 0 2]
[1 1 0 1 0 0 3 3 0 0]
[2 1 2 0 0 2 3 2 1 0]
[0 0 1 1 0

[0 2 0 2 0 2 2 0 0 0]
[0 3 2 1 0 4 2 0 3 0]
[0 0 2 1 2 0 0 0 3 2]
[0 0 1 1 0 0 1 0 1 0]
[2 1 1 1 0 2 2 2 3 1]
[1 0 1 0 2 2 0 0 1 2]
[4 1 0 0 0 1 0 0 2 0]
[4 3 0 0 1 0 0 1 0 0]
[1 3 0 0 0 1 2 2 0 0]
[0 2 0 2 0 0 0 1 1 0]
[2 0 2 2 2 1 0 1 1 0]
[2 0 2 2 1 1 0 0 2 2]
[0 1 0 2 4 0 2 0 0 0]
[1 2 1 1 0 0 0 0 2 0]
[2 0 0 1 1 1 0 1 0 1]
[2 1 2 1 0 2 3 1 1 0]
[1 2 2 0 0 1 2 0 2 0]
[3 0 0 0 1 1 0 0 1 1]
[2 3 0 2 0 2 0 0 1 0]
[2 0 0 0 2 1 2 0 1 2]
[1 0 0 0 2 0 0 1 0 2]
[0 0 2 0 1 0 1 2 2 0]
[0 0 1 2 0 0 0 2 1 2]
[0 2 1 1 0 0 1 1 0 0]
[1 1 1 0 0 1 0 0 4 1]
[2 0 0 0 3 1 2 0 0 2]
[0 0 0 0 0 0 0 1 0 1]
[3 2 1 2 0 0 2 2 1 0]
[0 0 2 0 1 0 0 0 1 1]
[1 2 2 0 0 0 0 3 1 1]
[0 0 0 1 3 1 1 3 0 0]
[0 2 0 3 0 2 2 0 1 1]
[2 1 1 0 1 1 1 0 0 1]
[0 0 3 2 0 1 0 2 1 0]
[0 1 0 3 1 1 1 0 0 0]
[3 2 0 3 2 2 0 0 3 3]
[1 0 0 0 0 0 1 0 0 0]
[2 0 1 0 2 0 0 2 1 0]
[1 2 2 1 0 0 0 0 0 1]
[1 0 0 2 1 2 0 2 0 2]
[0 2 4 0 3 1 2 2 1 3]
[0 0 2 0 0 3 1 0 3 0]
[0 0 2 0 0 0 2 1 1 0]
[1 2 2 1 0 0 0 4 0 0]
[0 2 2 0 1 1 1 4 1 2]
[1 0 2 0 0

[1 0 2 2 1 2 0 3 1 0]
[1 1 1 2 1 2 1 1 2 2]
[1 1 2 1 0 1 1 0 1 0]
[1 0 0 0 0 2 2 0 3 1]
[1 2 2 0 0 1 1 0 0 0]
[0 0 1 2 1 2 1 3 1 1]
[1 1 0 1 1 3 3 3 4 0]
[2 1 0 2 0 0 3 0 1 2]
[1 2 0 0 2 0 1 0 2 0]
[2 2 1 3 3 3 0 2 0 1]
[0 2 3 1 0 0 1 2 0 0]
[2 2 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 0 2]
[0 0 2 1 2 0 1 0 0 3]
[4 1 0 2 2 3 2 0 1 1]
[0 0 0 1 4 0 2 3 0 0]
[0 2 1 1 3 1 2 3 0 1]
[2 0 0 0 0 2 0 0 0 2]
[2 1 1 0 0 0 0 2 0 0]
[2 1 1 2 2 2 0 0 0 0]
[1 1 3 2 3 2 1 0 1 0]
[0 0 0 1 2 0 1 2 0 1]
[1 1 2 0 2 1 0 1 1 0]
[1 0 1 2 3 1 2 0 1 2]
[0 2 0 2 0 1 0 2 0 0]
[1 0 0 0 1 2 0 0 0 0]
[0 1 3 1 0 2 1 1 0 0]
[4 4 1 0 3 2 2 0 1 0]
[1 1 4 1 0 1 1 0 0 2]
[3 0 0 3 3 1 1 0 0 2]
[4 2 1 0 3 1 2 0 0 2]
[2 2 1 2 1 1 0 2 0 2]
[2 2 0 2 3 0 0 1 0 2]
[0 2 2 0 0 0 1 0 2 1]
[1 0 1 1 1 0 1 1 0 0]
[0 0 2 0 2 1 1 2 2 1]
[1 1 3 0 2 0 0 1 3 0]
[0 0 1 1 1 2 3 0 0 0]
[0 0 0 0 0 0 3 0 2 0]
[0 2 2 0 0 0 1 2 1 0]
[1 1 0 2 0 0 2 0 0 0]
[3 2 1 0 2 1 0 0 0 0]
[1 0 4 3 2 1 0 3 2 1]
[0 1 0 0 2 2 1 0 0 0]
[0 0 0 2 3 2 1 2 3 0]
[2 1 0 1 0

[2 0 3 0 0 0 0 0 0 0]
[1 0 2 0 0 1 1 0 0 1]
[1 0 0 1 0 1 2 0 1 0]
[1 0 0 0 0 0 0 2 0 2]
[3 0 0 0 1 0 0 0 2 1]
[2 0 0 0 2 0 1 1 0 1]
[0 1 1 2 0 1 0 0 0 0]
[3 0 0 0 1 0 0 1 1 1]
[0 0 0 1 1 1 0 1 1 0]
[1 0 0 1 3 1 1 1 0 0]
[0 1 2 1 1 0 2 1 0 0]
[2 2 1 0 0 0 1 3 0 1]
[1 2 0 0 1 0 1 1 3 0]
[4 2 1 2 0 1 1 3 1 0]
[0 1 1 2 1 0 1 1 1 1]
[1 0 1 1 1 0 1 2 0 0]
[0 3 1 0 0 0 0 0 1 1]
[2 0 1 1 2 2 1 0 1 1]
[0 3 2 0 1 2 1 2 1 1]
[0 3 3 1 0 0 0 0 0 2]
[1 1 0 1 0 0 0 0 1 1]
[0 1 1 0 2 2 0 4 2 4]
[2 0 0 0 3 2 1 1 1 3]
[1 2 0 1 0 0 0 0 1 0]
[0 2 0 0 0 1 2 1 1 1]
[0 3 0 0 2 0 1 0 3 0]
[0 1 1 0 3 0 2 1 0 0]
[1 0 2 0 1 4 3 0 2 2]
[2 0 1 0 2 2 1 0 2 0]
[1 1 1 2 1 0 3 0 0 0]
[0 1 1 2 0 2 1 3 0 2]
[3 1 0 4 0 2 1 0 0 0]
[0 1 0 2 0 1 1 0 2 0]
[1 0 0 0 2 0 1 1 2 3]
[1 1 0 0 0 0 0 0 1 1]
[1 2 1 2 1 0 1 1 0 1]
[2 1 2 0 1 0 0 0 0 0]
[0 1 2 0 2 1 0 2 1 0]
[0 2 2 1 2 0 2 1 1 0]
[0 0 1 3 2 2 1 0 2 0]
[0 0 0 2 1 0 2 2 1 1]
[1 1 1 0 0 2 1 1 0 2]
[1 1 0 0 2 0 3 2 2 2]
[2 2 0 1 0 2 1 2 0 3]
[2 0 0 1 2 0 1 1 0 2]
[1 0 0 2 1

[0 0 1 1 0 2 1 1 0 2]
[1 1 0 0 1 0 0 2 0 1]
[0 0 3 0 1 0 0 0 0 0]
[2 0 0 2 1 0 0 2 0 0]
[2 0 1 2 1 0 1 2 0 0]
[0 1 3 0 3 0 0 1 2 1]
[1 0 2 0 0 2 0 0 2 0]
[2 1 0 0 1 0 0 1 2 0]
[0 0 3 1 2 0 0 1 1 0]
[0 0 1 0 3 0 0 0 0 2]
[0 3 0 1 0 1 0 2 2 1]
[0 0 3 0 1 1 1 0 0 1]
[0 0 1 1 0 1 1 2 0 0]
[0 0 0 0 0 1 0 1 0 0]
[0 1 3 2 2 3 3 0 4 0]
[0 3 2 0 0 0 0 0 1 0]
[0 2 0 3 0 1 0 2 0 2]
[4 3 0 1 0 3 2 0 2 1]
[0 0 1 0 1 0 0 1 0 0]
[3 3 0 1 0 2 0 3 1 1]
[1 1 0 0 3 0 1 0 0 3]
[0 0 3 3 0 0 1 0 2 1]
[2 1 2 1 0 1 1 0 0 0]
[1 2 0 4 0 1 3 3 2 3]
[0 0 1 0 0 0 1 0 0 1]
[0 1 2 3 0 4 0 0 0 0]
[0 0 0 0 0 0 0 2 0 1]
[1 1 2 2 0 2 2 3 0 0]
[2 1 0 0 2 1 2 0 1 0]
[0 0 3 0 2 4 2 1 3 0]
[1 2 2 1 3 1 1 2 0 0]
[3 0 2 1 0 2 0 0 0 0]
[4 1 0 1 4 2 2 0 0 1]
[2 0 2 0 1 0 0 2 3 0]
[1 0 0 0 2 0 0 2 0 0]
[0 1 0 0 1 0 0 0 1 2]
[0 3 0 2 0 0 1 1 2 1]
[0 0 3 2 3 0 0 3 0 0]
[1 2 0 0 3 0 2 0 0 3]
[1 2 1 1 1 0 2 2 0 2]
[2 0 0 1 0 2 0 0 2 0]
[1 1 0 0 0 0 1 1 0 1]
[0 0 3 1 0 1 1 2 2 0]
[0 3 1 0 1 0 0 2 2 2]
[0 0 0 0 0 0 0 0 1 2]
[1 0 3 2 1

[2 0 1 0 3 3 1 1 1 0]
[3 2 1 1 2 2 0 0 1 0]
[0 0 0 0 2 3 2 0 1 0]
[0 0 0 1 0 1 0 0 0 1]
[3 0 1 2 2 2 0 2 1 0]
[0 0 0 0 1 0 0 1 0 2]
[0 1 1 1 0 0 0 1 4 0]
[0 2 3 1 0 0 2 0 0 1]
[0 1 1 0 2 1 2 2 0 2]
[0 1 1 2 0 0 0 0 1 1]
[1 0 0 0 2 2 3 0 1 2]
[1 0 1 0 1 2 0 0 2 1]
[2 1 0 2 0 0 3 1 1 1]
[1 0 0 0 2 0 2 0 1 0]
[0 0 0 1 0 0 2 1 0 2]
[0 0 0 4 0 0 0 0 1 3]
[1 1 3 0 0 0 1 0 0 0]
[0 0 1 1 0 2 3 1 0 1]
[2 0 0 1 0 1 1 1 2 0]
[0 0 1 3 0 1 0 0 0 2]
[0 0 1 0 0 0 0 0 0 0]
[0 4 0 1 1 0 0 2 3 2]
[3 0 1 1 2 2 0 0 0 2]
[1 1 2 1 2 0 2 1 0 0]
[1 0 0 3 0 3 1 1 2 0]
[0 1 2 0 1 0 1 1 1 2]
[0 0 1 0 2 0 4 1 0 0]
[0 0 3 3 0 2 0 2 0 1]
[1 2 0 1 0 2 1 3 1 2]
[0 0 0 1 0 2 0 0 1 1]
[1 1 2 2 0 2 3 0 1 2]
[1 1 0 0 2 0 1 1 1 0]
[2 2 0 1 1 0 0 0 1 0]
[2 1 0 1 0 1 1 1 1 0]
[1 2 0 2 0 0 1 3 0 1]
[2 1 0 2 0 0 0 0 1 0]
[1 2 3 3 0 1 1 0 1 1]
[3 0 4 2 3 0 1 1 2 0]
[2 0 1 0 2 2 1 1 3 0]
[0 1 1 3 1 0 0 0 0 0]
[0 2 1 2 0 0 1 2 0 0]
[0 0 3 2 1 2 3 0 0 0]
[0 2 0 0 0 0 3 1 1 2]
[2 2 1 1 1 2 0 0 1 0]
[1 4 2 2 0 3 0 1 1 0]
[0 3 3 0 2

[1 1 0 1 0 0 1 0 0 0]
[1 1 2 1 1 1 0 1 1 0]
[0 2 2 1 1 0 0 1 1 0]
[2 1 0 0 2 1 1 0 1 4]
[1 1 2 0 1 0 0 0 2 0]
[1 2 1 1 0 1 2 0 2 2]
[0 1 1 0 1 3 1 4 1 4]
[3 0 0 3 0 0 0 0 0 1]
[1 0 2 2 0 1 2 1 0 1]
[0 2 0 0 2 1 3 1 0 2]
[0 0 1 1 1 0 0 0 1 0]
[2 0 1 2 2 1 3 0 3 2]
[0 2 0 0 0 0 2 2 3 0]
[0 0 0 1 0 1 2 0 2 0]
[1 1 0 3 1 0 0 2 1 1]
[2 3 3 0 0 1 0 3 0 0]
[1 2 0 2 2 0 2 1 2 1]
[0 2 0 0 2 0 1 3 1 1]
[0 0 1 1 2 1 1 0 0 0]
[2 1 1 1 2 0 0 1 0 0]
[0 1 2 2 1 1 2 1 1 0]
[2 3 1 0 2 0 2 2 4 1]
[3 1 2 0 1 2 0 0 1 2]
[2 1 0 1 1 1 2 0 0 3]
[0 1 1 0 0 0 0 4 0 3]
[0 0 0 1 3 0 0 2 0 2]
[0 2 2 1 0 2 1 0 0 0]
[1 0 1 1 0 1 2 1 1 0]
[0 1 1 0 0 2 0 0 0 2]
[1 4 0 2 0 0 2 0 0 2]
[1 0 0 0 1 0 1 0 3 0]
[0 1 1 0 0 0 0 0 1 0]
[0 2 0 2 0 0 1 2 1 0]
[3 1 0 0 1 1 0 1 0 0]
[0 0 2 1 1 0 0 1 0 2]
[2 2 0 1 0 1 0 2 1 1]
[1 0 1 0 1 0 0 0 1 2]
[0 1 0 3 2 1 2 2 1 2]
[1 2 1 2 1 0 1 0 0 3]
[0 2 0 0 0 1 2 1 0 0]
[1 0 0 0 0 0 1 1 0 2]
[0 1 2 0 3 1 0 0 2 0]
[1 2 2 3 1 0 3 0 0 1]
[0 2 0 2 0 0 1 2 1 1]
[1 0 0 2 1 1 2 1 0 3]
[0 0 0 2 0

[2 2 1 0 2 2 1 0 2 0]
[1 2 2 0 0 0 2 0 1 0]
[0 2 0 2 0 0 0 1 1 0]
[0 0 0 1 0 0 0 1 0 0]
[0 0 0 1 2 0 3 0 2 1]
[0 3 0 0 0 3 0 0 1 1]
[2 3 2 0 0 1 0 2 3 1]
[2 0 0 2 1 0 3 2 2 2]
[2 0 0 0 0 0 1 1 2 1]
[2 2 1 0 1 0 0 0 0 1]
[0 1 1 0 2 0 0 0 0 1]
[0 2 1 4 0 2 1 1 0 1]
[2 2 0 0 0 0 1 0 1 2]
[2 1 2 1 0 1 1 3 2 0]
[1 1 3 2 3 0 3 0 0 1]
[3 2 1 0 1 0 1 0 2 1]
[3 1 2 0 1 0 0 2 3 3]
[2 2 1 0 2 0 0 1 3 0]
[0 1 0 0 1 0 0 1 0 1]
[0 2 1 0 1 1 1 0 0 0]
[1 1 0 0 0 1 0 0 1 1]
[0 0 1 0 2 1 1 0 2 0]
[1 0 0 0 1 4 0 0 4 2]
[0 0 2 0 0 1 1 1 3 1]
[0 0 1 2 0 0 1 2 1 2]
[1 2 1 3 1 1 0 3 2 0]
[2 2 1 1 0 1 3 0 1 1]

KeyboardInterrupt: 